"""v83 patch: 7 new concepts from classic-game codex analysis.

gravity_platformer  -- jump-over-obstacles platformer mechanic
shoot_and_move      -- fire shoot action rhythmically while navigating
beat_sync           -- timed interval actions for rhythm/QTE games
menu_navigate       -- directional menu cycling + confirm
dodge_reactive      -- reverse direction on score loss (threat reaction)
racing_steer        -- hold accelerate + steer by score signal
inventory_chain     -- scan→approach→use (pick up + equip + apply)
"""

import json

NEW_CONCEPTS = (
    "\n"
    "        elif concept == 'gravity_platformer':\n"
    "            # Platformer jump mechanic: run right, jump when stuck.\n"
    "            # A1=jump, A4=right, A3=left. Detects wall stalls (no frame\n"
    "            # change) and fires a jump+run sequence to clear obstacles.\n"
    "            # Good for: Mario, Mega Man, Contra, Castlevania, Celeste.\n"
    "            if '_gp_steps' not in self._pipeline_context:\n"
    "                self._pipeline_context['_gp_steps']     = 0\n"
    "                self._pipeline_context['_gp_stuck']     = 0\n"
    "                self._pipeline_context['_gp_phase']     = 'run'\n"
    "                self._pipeline_context['_gp_phase_cnt'] = 0\n"
    "                self._pipeline_context['_gp_favor_dir'] = 4\n"
    "            _gp_steps = self._pipeline_context['_gp_steps'] + 1\n"
    "            _gp_stuck = self._pipeline_context['_gp_stuck']\n"
    "            _gp_phase = self._pipeline_context['_gp_phase']\n"
    "            _gp_pcnt  = self._pipeline_context['_gp_phase_cnt']\n"
    "            _gp_fdir  = self._pipeline_context['_gp_favor_dir']\n"
    "            _gp_prod  = context.get('last_was_productive', False)\n"
    "            if not _gp_prod: _gp_stuck += 1\n"
    "            else: _gp_stuck = 0\n"
    "            if _gp_phase == 'run':\n"
    "                if _gp_stuck >= 2:\n"
    "                    _gp_phase = 'jump'\n"
    "                    _gp_pcnt  = 0\n"
    "                    _gp_stuck = 0\n"
    "                act = _gp_fdir if _gp_fdir in (move_actions or [4]) else (move_actions or [4])[0]\n"
    "            elif _gp_phase == 'jump':\n"
    "                if _gp_pcnt == 0:\n"
    "                    act = 1  # jump\n"
    "                elif _gp_pcnt <= 3:\n"
    "                    act = _gp_fdir if _gp_fdir in (move_actions or [4]) else (move_actions or [4])[0]\n"
    "                else:\n"
    "                    _gp_phase = 'run'\n"
    "                    _gp_pcnt  = -1\n"
    "                    act = _gp_fdir if _gp_fdir in (move_actions or [4]) else (move_actions or [4])[0]\n"
    "                _gp_pcnt += 1\n"
    "            else:\n"
    "                _gp_phase = 'run'\n"
    "                act = _gp_fdir if _gp_fdir in (move_actions or [4]) else (move_actions or [4])[0]\n"
    "            # After many steps: alternate favor direction\n"
    "            if _gp_steps % 40 == 0 and move_actions:\n"
    "                _gp_fdir = move_actions[(_gp_steps // 40) % len(move_actions)]\n"
    "            if act not in avail: act = (move_actions or list(avail))[0]\n"
    "            self._pipeline_context.update({\n"
    "                '_gp_steps': _gp_steps, '_gp_stuck': _gp_stuck,\n"
    "                '_gp_phase': _gp_phase, '_gp_phase_cnt': _gp_pcnt,\n"
    "                '_gp_favor_dir': _gp_fdir,\n"
    "            })\n"
    "            return act, None, (\n"
    "                f'gravity_plat:{_gp_phase} A{act} stuck={_gp_stuck}')\n"
    "\n"
    "        elif concept == 'shoot_and_move':\n"
    "            # Fire shoot action every N steps while navigating laterally.\n"
    "            # Good for: run-and-gun shooters, side-scrollers with projectiles,\n"
    "            # any game needing sustained attack + movement simultaneously.\n"
    "            # Shoot = any non-move non-click commit action.\n"
    "            _SM_FIRE_FREQ = 2\n"
    "            if '_sm_steps' not in self._pipeline_context:\n"
    "                self._pipeline_context['_sm_steps']   = 0\n"
    "                self._pipeline_context['_sm_dir']     = (move_actions or [4])[0]\n"
    "                self._pipeline_context['_sm_stuck']   = 0\n"
    "            _sm_steps = self._pipeline_context['_sm_steps'] + 1\n"
    "            _sm_dir   = self._pipeline_context['_sm_dir']\n"
    "            _sm_stuck = self._pipeline_context['_sm_stuck']\n"
    "            _sm_prod  = context.get('last_was_productive', False)\n"
    "            _sm_shoot = [a for a in avail if a not in {1, 2, 3, 4, 6}]\n"
    "            if not _sm_prod: _sm_stuck += 1\n"
    "            else: _sm_stuck = 0\n"
    "            if _sm_stuck >= 3 and move_actions:\n"
    "                _sm_dir   = move_actions[(_sm_steps // 3) % len(move_actions)]\n"
    "                _sm_stuck = 0\n"
    "            if _sm_shoot and _sm_steps % _SM_FIRE_FREQ == 0:\n"
    "                act = _sm_shoot[0]\n"
    "                label = f'shoot_move:FIRE A{act}'\n"
    "            elif move_actions:\n"
    "                _sm_dir = _sm_dir if _sm_dir in move_actions else move_actions[0]\n"
    "                act = _sm_dir\n"
    "                label = f'shoot_move:NAV A{act}'\n"
    "            else:\n"
    "                act = _rb_random.choice(list(avail))\n"
    "                label = f'shoot_move:RAND A{act}'\n"
    "            self._pipeline_context.update({\n"
    "                '_sm_steps': _sm_steps, '_sm_dir': _sm_dir, '_sm_stuck': _sm_stuck,\n"
    "            })\n"
    "            return act, None, label\n"
    "\n"
    "        elif concept == 'beat_sync':\n"
    "            # Fire actions at rhythmic beat intervals.\n"
    "            # Good for: rhythm games, QTE prompts, mash-timing events,\n"
    "            # Track & Field button mashing, any time-critical input.\n"
    "            # Fires confirm/click on the beat, navigates off-beat.\n"
    "            _BS_BEAT = 3  # steps per beat\n"
    "            if '_bs_step' not in self._pipeline_context:\n"
    "                self._pipeline_context['_bs_step'] = 0\n"
    "            _bs_step    = self._pipeline_context['_bs_step'] + 1\n"
    "            _bs_commits = [a for a in avail if a not in {1, 2, 3, 4}]\n"
    "            on_beat = (_bs_step % _BS_BEAT == 0)\n"
    "            if on_beat and _bs_commits:\n"
    "                act = _bs_commits[0]\n"
    "                if act == 6:\n"
    "                    _bx = (_bs_step * 7 + 8) % 56 + 4\n"
    "                    _by = (_bs_step * 11 + 8) % 56 + 4\n"
    "                    self._pipeline_context['_bs_step'] = _bs_step\n"
    "                    return 6, {'x': _bx, 'y': _by}, (\n"
    "                        f'beat_sync:BEAT click ({_bx},{_by}) step={_bs_step}')\n"
    "                self._pipeline_context['_bs_step'] = _bs_step\n"
    "                return act, None, f'beat_sync:BEAT A{act} step={_bs_step}'\n"
    "            # Off-beat: navigate or hold direction\n"
    "            if move_actions:\n"
    "                act = move_actions[(_bs_step // _BS_BEAT) % len(move_actions)]\n"
    "            else:\n"
    "                act = list(avail)[_bs_step % len(avail)]\n"
    "            self._pipeline_context['_bs_step'] = _bs_step\n"
    "            return act, None, f'beat_sync:OFF A{act} step={_bs_step}'\n"
    "\n"
    "        elif concept == 'menu_navigate':\n"
    "            # Navigate directional menus and confirm selections.\n"
    "            # Good for: RPG battle menus, inventory screens, option lists,\n"
    "            # Final Fantasy, Dragon Warrior, XCOM, any menu-driven game.\n"
    "            # Cycles directional actions, confirms every N steps.\n"
    "            _MN_CONFIRM_EVERY = 4\n"
    "            if '_mn_steps' not in self._pipeline_context:\n"
    "                self._pipeline_context['_mn_steps']   = 0\n"
    "                self._pipeline_context['_mn_dir_idx'] = 0\n"
    "                self._pipeline_context['_mn_confirmed'] = 0\n"
    "            _mn_steps = self._pipeline_context['_mn_steps'] + 1\n"
    "            _mn_didx  = self._pipeline_context['_mn_dir_idx']\n"
    "            _mn_conf  = self._pipeline_context['_mn_confirmed']\n"
    "            _mn_dirs  = move_actions or [1, 2, 3, 4]\n"
    "            _mn_cmts  = [a for a in avail if a not in {1, 2, 3, 4}]\n"
    "            if _mn_cmts and _mn_steps % _MN_CONFIRM_EVERY == 0:\n"
    "                act = _mn_cmts[0]\n"
    "                _mn_conf += 1\n"
    "                if act == 6:\n"
    "                    self._pipeline_context.update({\n"
    "                        '_mn_steps': _mn_steps, '_mn_confirmed': _mn_conf,\n"
    "                    })\n"
    "                    return 6, {'x': 32, 'y': 40}, (\n"
    "                        f'menu_nav:CONFIRM click step={_mn_steps}')\n"
    "                self._pipeline_context.update({\n"
    "                    '_mn_steps': _mn_steps, '_mn_confirmed': _mn_conf,\n"
    "                })\n"
    "                return act, None, f'menu_nav:CONFIRM A{act} step={_mn_steps}'\n"
    "            # Navigate: advance direction every 2 steps\n"
    "            _mn_didx = _mn_didx % len(_mn_dirs)\n"
    "            act = _mn_dirs[_mn_didx]\n"
    "            if _mn_steps % 2 == 0:\n"
    "                _mn_didx = (_mn_didx + 1) % len(_mn_dirs)\n"
    "            self._pipeline_context.update({\n"
    "                '_mn_steps': _mn_steps, '_mn_dir_idx': _mn_didx,\n"
    "            })\n"
    "            return act, None, f'menu_nav:DIR A{act} step={_mn_steps}'\n"
    "\n"
    "        elif concept == 'dodge_reactive':\n"
    "            # React to score loss by reversing direction (threat avoidance).\n"
    "            # Good for: Dark Souls, Cuphead, bullet hell, any game where\n"
    "            # incorrect movement causes immediate score penalty.\n"
    "            # On score drop: pivot perpendicular; otherwise advance.\n"
    "            if '_dr_dir' not in self._pipeline_context:\n"
    "                self._pipeline_context['_dr_dir']      = (move_actions or [4])[0]\n"
    "                self._pipeline_context['_dr_dodges']   = 0\n"
    "                self._pipeline_context['_dr_steps']    = 0\n"
    "            _dr_steps  = self._pipeline_context['_dr_steps'] + 1\n"
    "            _dr_dir    = self._pipeline_context['_dr_dir']\n"
    "            _dr_dodges = self._pipeline_context['_dr_dodges']\n"
    "            _dr_delta  = context.get('score_delta', 0) or 0\n"
    "            _dr_prod   = context.get('last_was_productive', False)\n"
    "            _dr_dirs   = move_actions or [1, 2, 3, 4]\n"
    "            _reverse   = {1: 2, 2: 1, 3: 4, 4: 3}\n"
    "            if _dr_delta < 0:\n"
    "                _dr_dodges += 1\n"
    "                # Perpendicular pivot: H→V, V→H\n"
    "                _h = [a for a in _dr_dirs if a in {3, 4}]\n"
    "                _v = [a for a in _dr_dirs if a in {1, 2}]\n"
    "                if _dr_dir in {3, 4} and _v:\n"
    "                    _dr_dir = _rb_random.choice(_v)\n"
    "                elif _h:\n"
    "                    _dr_dir = _rb_random.choice(_h)\n"
    "                else:\n"
    "                    _dr_dir = _reverse.get(_dr_dir, _dr_dirs[0])\n"
    "            elif not _dr_prod:\n"
    "                _dr_dir = _dr_dirs[_dr_steps % len(_dr_dirs)]\n"
    "            if _dr_dir not in avail and move_actions:\n"
    "                _dr_dir = move_actions[0]\n"
    "            # Check if commit helps\n"
    "            _dr_cmts = [a for a in avail if a not in {1,2,3,4,6}]\n"
    "            if _dr_cmts and _dr_steps % 7 == 0:\n"
    "                self._pipeline_context.update({\n"
    "                    '_dr_dir': _dr_dir, '_dr_dodges': _dr_dodges, '_dr_steps': _dr_steps,\n"
    "                })\n"
    "                return _dr_cmts[0], None, (\n"
    "                    f'dodge_react:COMMIT A{_dr_cmts[0]} dodges={_dr_dodges}')\n"
    "            self._pipeline_context.update({\n"
    "                '_dr_dir': _dr_dir, '_dr_dodges': _dr_dodges, '_dr_steps': _dr_steps,\n"
    "            })\n"
    "            return _dr_dir, None, (\n"
    "                f'dodge_react:A{_dr_dir} dodges={_dr_dodges} delta={_dr_delta}')\n"
    "\n"
    "        elif concept == 'racing_steer':\n"
    "            # Accelerate continuously, steer left/right based on score signal.\n"
    "            # Good for: racing games, OutRun, F-Zero, Road Rash,\n"
    "            # any forward-motion game with lane-keeping.\n"
    "            # Steer opposite when score drops.\n"
    "            _RS_ACCEL_ACTS = [2, 1]  # prefer A2 (down=gas), fallback A1\n"
    "            if '_rs_steer' not in self._pipeline_context:\n"
    "                self._pipeline_context['_rs_steer']   = 4  # start steering right\n"
    "                self._pipeline_context['_rs_steps']   = 0\n"
    "                self._pipeline_context['_rs_acc_n']   = 0\n"
    "                self._pipeline_context['_rs_steer_n'] = 0\n"
    "            _rs_steps  = self._pipeline_context['_rs_steps'] + 1\n"
    "            _rs_steer  = self._pipeline_context['_rs_steer']\n"
    "            _rs_acc_n  = self._pipeline_context['_rs_acc_n']\n"
    "            _rs_scnt   = self._pipeline_context['_rs_steer_n']\n"
    "            _rs_delta  = context.get('score_delta', 0) or 0\n"
    "            _rs_dirs   = move_actions or [1, 2, 3, 4]\n"
    "            # Score drop: flip steer direction\n"
    "            if _rs_delta < 0:\n"
    "                _flip = {3: 4, 4: 3, 1: 2, 2: 1}\n"
    "                _rs_steer = _flip.get(_rs_steer, 4)\n"
    "                _rs_scnt  = 0\n"
    "            # Find accel and steer actions in available\n"
    "            _accel = next((a for a in _RS_ACCEL_ACTS if a in _rs_dirs), _rs_dirs[0])\n"
    "            _steer_l = 3 if 3 in _rs_dirs else None\n"
    "            _steer_r = 4 if 4 in _rs_dirs else None\n"
    "            # Steer every 3rd step, accelerate otherwise\n"
    "            if _rs_scnt < 2 and _rs_steps % 3 == 0 and _rs_steer in _rs_dirs:\n"
    "                act = _rs_steer\n"
    "                _rs_scnt += 1\n"
    "            else:\n"
    "                act = _accel\n"
    "                _rs_acc_n += 1\n"
    "                if _rs_scnt >= 2: _rs_scnt = 0\n"
    "            self._pipeline_context.update({\n"
    "                '_rs_steer': _rs_steer, '_rs_steps': _rs_steps,\n"
    "                '_rs_acc_n': _rs_acc_n, '_rs_steer_n': _rs_scnt,\n"
    "            })\n"
    "            return act, None, (\n"
    "                f'racing_steer:A{act} steer={_rs_steer} delta={_rs_delta}')\n"
    "\n"
    "        elif concept == 'inventory_chain':\n"
    "            # 3-phase: scan grid for items (click), approach, then use commit.\n"
    "            # Good for: Zelda item pickup, adventure game object use,\n"
    "            # any game requiring pick-up + equip + apply sequence.\n"
    "            _IC_SCAN_GRID = [(x,y) for y in range(4,64,8) for x in range(4,64,8)]\n"
    "            if '_ic_phase' not in self._pipeline_context:\n"
    "                self._pipeline_context['_ic_phase']    = 'scan'\n"
    "                self._pipeline_context['_ic_sidx']     = 0\n"
    "                self._pipeline_context['_ic_item_pos'] = None\n"
    "                self._pipeline_context['_ic_nav_cnt']  = 0\n"
    "                self._pipeline_context['_ic_use_cnt']  = 0\n"
    "            _ic_phase = self._pipeline_context['_ic_phase']\n"
    "            _ic_sidx  = self._pipeline_context['_ic_sidx']\n"
    "            _ic_item  = self._pipeline_context['_ic_item_pos']\n"
    "            _ic_navs  = self._pipeline_context['_ic_nav_cnt']\n"
    "            _ic_use   = self._pipeline_context['_ic_use_cnt']\n"
    "            _ic_prod  = context.get('last_was_productive', False)\n"
    "            _ic_cmts  = [a for a in avail if a not in {1, 2, 3, 4, 6}]\n"
    "            if _ic_phase == 'scan':\n"
    "                if _ic_prod:\n"
    "                    _ic_item  = _IC_SCAN_GRID[max(0, _ic_sidx-1) % len(_IC_SCAN_GRID)]\n"
    "                    _ic_phase = 'approach' if move_actions else 'use'\n"
    "                    _ic_navs  = 0\n"
    "                if _ic_sidx >= len(_IC_SCAN_GRID): _ic_sidx = 0\n"
    "                _ix, _iy = _IC_SCAN_GRID[_ic_sidx % len(_IC_SCAN_GRID)]\n"
    "                _ic_sidx += 1\n"
    "                self._pipeline_context.update({\n"
    "                    '_ic_phase': _ic_phase, '_ic_sidx': _ic_sidx,\n"
    "                    '_ic_item_pos': _ic_item,\n"
    "                })\n"
    "                return 6, {'x': _ix, 'y': _iy}, (\n"
    "                    f'inv_chain:SCAN ({_ix},{_iy}) idx={_ic_sidx}')\n"
    "            elif _ic_phase == 'approach' and move_actions:\n"
    "                _ic_navs += 1\n"
    "                if _ic_navs >= 8 or not _ic_item:\n"
    "                    _ic_phase = 'use'\n"
    "                    _ic_navs  = 0\n"
    "                act = move_actions[_ic_navs % len(move_actions)]\n"
    "                self._pipeline_context.update({\n"
    "                    '_ic_phase': _ic_phase, '_ic_nav_cnt': _ic_navs,\n"
    "                })\n"
    "                return act, None, (\n"
    "                    f'inv_chain:APPROACH A{act} navs={_ic_navs}')\n"
    "            else:  # use phase\n"
    "                _ic_use += 1\n"
    "                if _ic_cmts and _ic_use <= 3:\n"
    "                    act = _ic_cmts[0]\n"
    "                    self._pipeline_context.update({'_ic_use_cnt': _ic_use})\n"
    "                    return act, None, (\n"
    "                        f'inv_chain:USE A{act} cnt={_ic_use}')\n"
    "                # Reset to scan, advance position\n"
    "                _ic_phase = 'scan'\n"
    "                _ic_sidx  = (_ic_sidx + 8) % len(_IC_SCAN_GRID)\n"
    "                self._pipeline_context.update({\n"
    "                    '_ic_phase': _ic_phase, '_ic_sidx': _ic_sidx, '_ic_use_cnt': 0,\n"
    "                })\n"
    "                _ix, _iy = _IC_SCAN_GRID[_ic_sidx % len(_IC_SCAN_GRID)]\n"
    "                return 6, {'x': _ix, 'y': _iy}, (\n"
    "                    f'inv_chain:SCAN_RST ({_ix},{_iy})')\n"
    "\n"
)

TARGET = "        # navigation / coverage / traversal_ordering / mixed_movement"

# Add new concepts to LONG_PATH_CONCEPTS
OLD_LONG = (
    "                'random_action', 'interact_seek', 'position_commit', 'momentum_build',\n"
    "     "
)
NEW_LONG = (
    "                'random_action', 'interact_seek', 'position_commit', 'momentum_build',\n"
    "                'gravity_platformer', 'shoot_and_move', 'racing_steer',\n"
    "                'dodge_reactive', 'pursuit_evade', 'stealth_patrol_wait',\n"
    "                'physics_probe',\n"
    "     "
)

# Add routing: shoot_and_move for movement + commit games (more aggressive than interact_seek)
OLD_INTERACT_ROUTE = (
    "            cands = ['interact_seek', 'position_commit', 'momentum_build'] + cands"
)
NEW_INTERACT_ROUTE = (
    "            cands = ['interact_seek', 'shoot_and_move', 'position_commit',\n"
    "                     'momentum_build', 'dodge_reactive'] + cands"
)

# Add gravity_platformer + racing_steer to maze prio block (movement-only no toggle)
OLD_MAZE_PRIO = (
    "            _maze_prio = ['greedy_productive', 'directional_sweep',\n"
    "                          'wall_follower', 'momentum_probe', 'oscillation_escape']"
)
NEW_MAZE_PRIO = (
    "            _maze_prio = ['greedy_productive', 'directional_sweep',\n"
    "                          'wall_follower', 'momentum_probe', 'oscillation_escape',\n"
    "                          'gravity_platformer', 'racing_steer', 'physics_probe']"
)

with open('bittertruth_ai_upload/competition_notebook_v2.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

cell = nb['cells'][11]
src = ''.join(cell.get('source', []))

assert TARGET in src, 'TARGET not found!'
assert OLD_LONG in src, f'OLD_LONG not found!'
assert OLD_INTERACT_ROUTE in src, f'OLD_INTERACT_ROUTE not found!'
assert OLD_MAZE_PRIO in src, f'OLD_MAZE_PRIO not found!'

src2 = src.replace(TARGET, NEW_CONCEPTS + TARGET, 1)
src2 = src2.replace(OLD_LONG, NEW_LONG, 1)
src2 = src2.replace(OLD_INTERACT_ROUTE, NEW_INTERACT_ROUTE, 1)
src2 = src2.replace(OLD_MAZE_PRIO, NEW_MAZE_PRIO, 1)

assert src2 != src
print(f'Added {len(src2) - len(src)} chars')

nb['cells'][11]['source'] = [src2]

src10 = ''.join(nb['cells'][10].get('source', []))
src10_new = src10.replace("_SOLVER_VERSION = 'v82.0'", "_SOLVER_VERSION = 'v83.0'")
assert src10_new != src10
nb['cells'][10]['source'] = [src10_new]

with open('bittertruth_ai_upload/competition_notebook_v2.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f)
print('Done v83')
