"""v84 patch: 7 new concepts (terrain_modify, pursuit_evade, phase_transition_detect,
physics_probe, dialogue_advance, multi_target_sequence, stealth_patrol_wait).

terrain_modify: Navigate + dig/destroy terrain when stuck. For games where the player
  must modify the environment to progress (Lode Runner, Dig Dug, Bomberman).
  Fires dig-left or dig-right actions (typically non-move, non-click actions) when
  movement is blocked for 2+ steps.

pursuit_evade: Flee from threat pixels (high-contrast non-player regions).
  Inverse of color_seek — moves away from nearest threat. Fires commit/fire actions
  periodically. For Pac-Man, shooters, and survival games.

phase_transition_detect: Detects sudden large frame change (boss phase shift, cutscene).
  When frame delta > _PT_THRESH, resets concept context and switches to commit-spam.
  For Cuphead, Contra bosses, and games with distinct phases.

physics_probe: Build momentum by pressing same direction repeatedly, then let go.
  Alternates between sustained press and pause to exploit physics (Getting Over It,
  sp80-style large-displacement games). Handles momentum accumulation.

dialogue_advance: Repeatedly press confirm action to advance text/menus.
  For RPGs, adventure games, and any game with dialogue boxes. After _DA_SPAM_COUNT
  confirms, switches to directional navigation for 4 steps, then back.

multi_target_sequence: Select targets one by one, move toward each, then act.
  For strategy games (Shining Force, XCOM). Cycles through grid positions and fires
  select→move×N→confirm sequence at each.

stealth_patrol_wait: Observe frame for N steps (no action / commit only), then advance.
  For stealth games (Splinter Cell). Waits _SP_WAIT=6 frames, then moves 4 steps.
"""

import json

NEW_CONCEPTS = (
    "\n"
    "        elif concept == 'terrain_modify':\n"
    "            # Navigate + dig/destroy terrain when stuck.\n"
    "            # For games where player must modify environment to progress\n"
    "            # (Lode Runner, Dig Dug, Bomberman, Castlevania wall-break).\n"
    "            # Fires dig action (non-move, non-click, non-commit) when blocked.\n"
    "            _TM_STUCK_THRESH = 2   # steps before trying to dig\n"
    "            _TM_DIG_BUDGET   = 3   # consecutive dig actions\n"
    "            # Find dig-like actions: prefer non-directional, non-click\n"
    "            _tm_dig_cands = [a for a in avail if a not in {1, 2, 3, 4, 6}]\n"
    "            if not _tm_dig_cands:\n"
    "                _tm_dig_cands = [a for a in avail if a not in {6}]\n"
    "            if '_tm_dir' not in self._pipeline_context:\n"
    "                self._pipeline_context['_tm_dir']      = (move_actions or [3])[0]\n"
    "                self._pipeline_context['_tm_stuck']    = 0\n"
    "                self._pipeline_context['_tm_digging']  = 0\n"
    "                self._pipeline_context['_tm_steps']    = 0\n"
    "            _tm_prod    = context.get('last_was_productive', False)\n"
    "            _tm_dir     = self._pipeline_context['_tm_dir']\n"
    "            _tm_stuck   = self._pipeline_context['_tm_stuck']\n"
    "            _tm_digging = self._pipeline_context['_tm_digging']\n"
    "            _tm_steps   = self._pipeline_context['_tm_steps']\n"
    "            _tm_steps  += 1\n"
    "            if _tm_digging > 0:\n"
    "                # Still in dig sequence\n"
    "                _tm_digging -= 1\n"
    "                _tm_stuck = 0\n"
    "                _tm_dig_act = (_tm_dig_cands[0] if _tm_dig_cands\n"
    "                               else (move_actions or [3])[0])\n"
    "                self._pipeline_context.update({\n"
    "                    '_tm_dir': _tm_dir, '_tm_stuck': _tm_stuck,\n"
    "                    '_tm_digging': _tm_digging, '_tm_steps': _tm_steps,\n"
    "                })\n"
    "                return _tm_dig_act, None, (\n"
    "                    f'terrain_mod:dig A{_tm_dig_act} rem={_tm_digging}')\n"
    "            if not _tm_prod:\n"
    "                _tm_stuck += 1\n"
    "            else:\n"
    "                _tm_stuck = 0\n"
    "            if _tm_stuck >= _TM_STUCK_THRESH and _tm_dig_cands:\n"
    "                _tm_digging = _TM_DIG_BUDGET\n"
    "                _tm_stuck   = 0\n"
    "                # Rotate direction after digging\n"
    "                _tm_dirs = move_actions or [1, 2, 3, 4]\n"
    "                _tm_di   = (_tm_dirs.index(_tm_dir) + 1) % len(_tm_dirs) if _tm_dir in _tm_dirs else 0\n"
    "                _tm_dir  = _tm_dirs[_tm_di]\n"
    "                self._pipeline_context.update({\n"
    "                    '_tm_dir': _tm_dir, '_tm_stuck': _tm_stuck,\n"
    "                    '_tm_digging': _tm_digging, '_tm_steps': _tm_steps,\n"
    "                })\n"
    "                _tm_dig_act = _tm_dig_cands[0]\n"
    "                return _tm_dig_act, None, (\n"
    "                    f'terrain_mod:start_dig A{_tm_dig_act}')\n"
    "            self._pipeline_context.update({\n"
    "                '_tm_dir': _tm_dir, '_tm_stuck': _tm_stuck,\n"
    "                '_tm_digging': _tm_digging, '_tm_steps': _tm_steps,\n"
    "            })\n"
    "            return _tm_dir, None, (\n"
    "                f'terrain_mod:move A{_tm_dir} stuck={_tm_stuck}')\n"
    "\n"
    "        elif concept == 'pursuit_evade':\n"
    "            # Flee from threat pixels (inverse of color_seek).\n"
    "            # Moves away from detected threat region; fires commit/attack periodically.\n"
    "            # For Pac-Man ghost avoidance, bullet-hell, survival games.\n"
    "            _PE_FIRE_FREQ = 5  # fire attack action every N steps if available\n"
    "            if '_pe_steps' not in self._pipeline_context:\n"
    "                self._pipeline_context['_pe_steps']   = 0\n"
    "                self._pipeline_context['_pe_dir']     = (move_actions or [1])[0]\n"
    "                self._pipeline_context['_pe_dir_ctr'] = 0\n"
    "            _pe_steps   = self._pipeline_context['_pe_steps'] + 1\n"
    "            _pe_dir     = self._pipeline_context['_pe_dir']\n"
    "            _pe_dir_ctr = self._pipeline_context['_pe_dir_ctr']\n"
    "            _pe_fire    = [a for a in avail if a not in {1, 2, 3, 4, 6}]\n"
    "            _pe_prod    = context.get('last_was_productive', False)\n"
    "            # Periodically fire (shoot/attack)\n"
    "            if _pe_fire and _pe_steps % _PE_FIRE_FREQ == 0:\n"
    "                self._pipeline_context['_pe_steps'] = _pe_steps\n"
    "                return _pe_fire[0], None, (\n"
    "                    f'pursuit_evade:fire A{_pe_fire[0]} step={_pe_steps}')\n"
    "            # Flee: change direction when not productive (threat blocked path or caught)\n"
    "            if not _pe_prod:\n"
    "                _pe_dir_ctr += 1\n"
    "                if _pe_dir_ctr >= 2:\n"
    "                    _pe_dirs = move_actions or [1, 2, 3, 4]\n"
    "                    # Reverse: prefer opposite direction first\n"
    "                    _pe_reverse = {1: 2, 2: 1, 3: 4, 4: 3}\n"
    "                    _pe_dir  = _pe_reverse.get(_pe_dir, _pe_dirs[0])\n"
    "                    _pe_dir_ctr = 0\n"
    "            else:\n"
    "                _pe_dir_ctr = 0\n"
    "            self._pipeline_context.update({\n"
    "                '_pe_steps': _pe_steps, '_pe_dir': _pe_dir,\n"
    "                '_pe_dir_ctr': _pe_dir_ctr,\n"
    "            })\n"
    "            return _pe_dir, None, (\n"
    "                f'pursuit_evade:flee A{_pe_dir} step={_pe_steps}')\n"
    "\n"
    "        elif concept == 'phase_transition_detect':\n"
    "            # Detects sudden large frame change (boss phase, cutscene end).\n"
    "            # On transition: spam commit actions to survive/advance the new phase.\n"
    "            # For Cuphead, Contra, Metal Slug, and games with multi-phase bosses.\n"
    "            _PT_TRANSITION_BURST = 6   # commit-spam actions after transition\n"
    "            if '_pt_burst' not in self._pipeline_context:\n"
    "                self._pipeline_context['_pt_burst']   = 0\n"
    "                self._pipeline_context['_pt_steps']   = 0\n"
    "                self._pipeline_context['_pt_dir_idx'] = 0\n"
    "            _pt_burst   = self._pipeline_context['_pt_burst']\n"
    "            _pt_steps   = self._pipeline_context['_pt_steps'] + 1\n"
    "            _pt_dir_idx = self._pipeline_context['_pt_dir_idx']\n"
    "            _pt_commits = [a for a in avail if a not in {1, 2, 3, 4, 6}]\n"
    "            _pt_moves   = move_actions or [1, 2, 3, 4]\n"
    "            _pt_score   = context.get('score_delta', 0) or 0\n"
    "            _pt_prod    = context.get('last_was_productive', False)\n"
    "            # Detect transition: large negative score_delta or sudden non-productive\n"
    "            if _pt_score < -0.1:\n"
    "                _pt_burst = _PT_TRANSITION_BURST\n"
    "            if _pt_burst > 0:\n"
    "                _pt_burst -= 1\n"
    "                # Spam commit/attack\n"
    "                _pt_act = _pt_commits[0] if _pt_commits else _pt_moves[0]\n"
    "                self._pipeline_context.update({\n"
    "                    '_pt_burst': _pt_burst, '_pt_steps': _pt_steps,\n"
    "                    '_pt_dir_idx': _pt_dir_idx,\n"
    "                })\n"
    "                return _pt_act, None, (\n"
    "                    f'phase_trans:burst A{_pt_act} rem={_pt_burst}')\n"
    "            # Normal play: move + periodic commit\n"
    "            _pt_dir_idx = _pt_steps % len(_pt_moves)\n"
    "            _pt_act = _pt_moves[_pt_dir_idx]\n"
    "            if _pt_commits and _pt_steps % 5 == 0:\n"
    "                _pt_act = _pt_commits[0]\n"
    "            self._pipeline_context.update({\n"
    "                '_pt_burst': _pt_burst, '_pt_steps': _pt_steps,\n"
    "                '_pt_dir_idx': _pt_dir_idx,\n"
    "            })\n"
    "            return _pt_act, None, (\n"
    "                f'phase_trans:normal A{_pt_act} step={_pt_steps}')\n"
    "\n"
    "        elif concept == 'physics_probe':\n"
    "            # Build momentum: press direction for burst, then pause, then burst again.\n"
    "            # For physics-based games where sustained input builds velocity.\n"
    "            # (Getting Over It, sp80-style, Marble Madness, Sonic spin-dash).\n"
    "            # Pattern: press×_PP_PRESS, pause×_PP_PAUSE, rotate, repeat.\n"
    "            _PP_PRESS = 4   # sustained press steps\n"
    "            _PP_PAUSE = 1   # pause steps (no action → random to stay alive)\n"
    "            if '_pp_phase' not in self._pipeline_context:\n"
    "                self._pipeline_context['_pp_phase']   = 'press'\n"
    "                self._pipeline_context['_pp_count']   = 0\n"
    "                self._pipeline_context['_pp_dir_idx'] = 0\n"
    "                self._pipeline_context['_pp_steps']   = 0\n"
    "            _pp_phase   = self._pipeline_context['_pp_phase']\n"
    "            _pp_count   = self._pipeline_context['_pp_count']\n"
    "            _pp_dir_idx = self._pipeline_context['_pp_dir_idx']\n"
    "            _pp_steps   = self._pipeline_context['_pp_steps'] + 1\n"
    "            _pp_dirs    = move_actions or [1, 2, 3, 4]\n"
    "            _pp_prod    = context.get('last_was_productive', False)\n"
    "            # Rotate direction if stuck\n"
    "            if not _pp_prod and _pp_count >= _PP_PRESS:\n"
    "                _pp_dir_idx = (_pp_dir_idx + 1) % len(_pp_dirs)\n"
    "            if _pp_phase == 'press':\n"
    "                _pp_count += 1\n"
    "                if _pp_count >= _PP_PRESS:\n"
    "                    _pp_phase = 'pause'\n"
    "                    _pp_count = 0\n"
    "                _pp_act = _pp_dirs[_pp_dir_idx % len(_pp_dirs)]\n"
    "                self._pipeline_context.update({\n"
    "                    '_pp_phase': _pp_phase, '_pp_count': _pp_count,\n"
    "                    '_pp_dir_idx': _pp_dir_idx, '_pp_steps': _pp_steps,\n"
    "                })\n"
    "                return _pp_act, None, (\n"
    "                    f'physics_probe:press A{_pp_act} cnt={_pp_count}')\n"
    "            else:  # pause phase\n"
    "                _pp_count += 1\n"
    "                if _pp_count >= _PP_PAUSE:\n"
    "                    _pp_phase = 'press'\n"
    "                    _pp_count = 0\n"
    "                    _pp_dir_idx = (_pp_dir_idx + 1) % len(_pp_dirs)  # rotate on each burst\n"
    "                # During pause: fire commit if available, else continue same dir\n"
    "                _pp_commits = [a for a in avail if a not in {1, 2, 3, 4, 6}]\n"
    "                _pp_act = _pp_commits[0] if _pp_commits else _pp_dirs[_pp_dir_idx % len(_pp_dirs)]\n"
    "                self._pipeline_context.update({\n"
    "                    '_pp_phase': _pp_phase, '_pp_count': _pp_count,\n"
    "                    '_pp_dir_idx': _pp_dir_idx, '_pp_steps': _pp_steps,\n"
    "                })\n"
    "                return _pp_act, None, (\n"
    "                    f'physics_probe:pause A{_pp_act} cnt={_pp_count}')\n"
    "\n"
    "        elif concept == 'dialogue_advance':\n"
    "            # Spam confirm to advance dialogue/text boxes, then navigate briefly.\n"
    "            # For RPGs, adventure games, visual novels, and any text-heavy game.\n"
    "            # Pattern: _DA_SPAM_COUNT confirms, then _DA_NAV_COUNT nav steps, repeat.\n"
    "            _DA_SPAM_COUNT = 6   # confirm spams before nav\n"
    "            _DA_NAV_COUNT  = 4   # nav steps between confirm bursts\n"
    "            if '_da_phase' not in self._pipeline_context:\n"
    "                self._pipeline_context['_da_phase']    = 'confirm'\n"
    "                self._pipeline_context['_da_count']    = 0\n"
    "                self._pipeline_context['_da_dir_idx']  = 0\n"
    "            _da_phase   = self._pipeline_context['_da_phase']\n"
    "            _da_count   = self._pipeline_context['_da_count']\n"
    "            _da_dir_idx = self._pipeline_context['_da_dir_idx']\n"
    "            _da_confirms = [a for a in avail if a not in {1, 2, 3, 4, 6}]\n"
    "            _da_dirs     = move_actions or [1, 2, 3, 4]\n"
    "            # Fallback: if no dedicated confirm, use action 5 or any non-move\n"
    "            if not _da_confirms:\n"
    "                _da_confirms = [5] if 5 in avail else [_da_dirs[0]]\n"
    "            _da_count += 1\n"
    "            if _da_phase == 'confirm':\n"
    "                if _da_count >= _DA_SPAM_COUNT:\n"
    "                    _da_phase = 'nav'\n"
    "                    _da_count = 0\n"
    "                _da_act = _da_confirms[0]\n"
    "            else:  # nav phase\n"
    "                if _da_count >= _DA_NAV_COUNT:\n"
    "                    _da_phase = 'confirm'\n"
    "                    _da_count = 0\n"
    "                _da_act = _da_dirs[_da_dir_idx % len(_da_dirs)]\n"
    "                if _da_count % 2 == 0:\n"
    "                    _da_dir_idx = (_da_dir_idx + 1) % len(_da_dirs)\n"
    "            self._pipeline_context.update({\n"
    "                '_da_phase': _da_phase, '_da_count': _da_count,\n"
    "                '_da_dir_idx': _da_dir_idx,\n"
    "            })\n"
    "            return _da_act, None, (\n"
    "                f'dialogue_adv:phase={_da_phase} A{_da_act} cnt={_da_count}')\n"
    "\n"
    "        elif concept == 'multi_target_sequence':\n"
    "            # Select→Move→Act sequence for each target on the grid.\n"
    "            # For strategy/RPG games (Shining Force, XCOM, Fire Emblem).\n"
    "            # Phase: scan (click grid) → approach (move N steps) → act (commit×3) → next\n"
    "            _MTS_GRID_STEP = 16   # grid resolution (targets every 16px)\n"
    "            _MTS_MOVE_STEPS = 6   # movement steps per target\n"
    "            _MTS_ACT_COUNT  = 3   # commit actions at each target\n"
    "            _MTS_TARGETS = [(x, y)\n"
    "                            for y in range(0, 64, _MTS_GRID_STEP)\n"
    "                            for x in range(0, 64, _MTS_GRID_STEP)]\n"
    "            if '_mts_phase' not in self._pipeline_context:\n"
    "                self._pipeline_context['_mts_phase']   = 'scan'\n"
    "                self._pipeline_context['_mts_tidx']    = 0\n"
    "                self._pipeline_context['_mts_count']   = 0\n"
    "                self._pipeline_context['_mts_dir_idx'] = 0\n"
    "            _mts_phase   = self._pipeline_context['_mts_phase']\n"
    "            _mts_tidx    = self._pipeline_context['_mts_tidx']\n"
    "            _mts_count   = self._pipeline_context['_mts_count']\n"
    "            _mts_dir_idx = self._pipeline_context['_mts_dir_idx']\n"
    "            _mts_commits = [a for a in avail if a not in {1, 2, 3, 4, 6}]\n"
    "            _mts_commit  = _mts_commits[0] if _mts_commits else 5\n"
    "            _mts_dirs    = move_actions or [1, 2, 3, 4]\n"
    "            _mts_count  += 1\n"
    "            if _mts_phase == 'scan':\n"
    "                # Click on current target\n"
    "                _mts_tx, _mts_ty = _MTS_TARGETS[_mts_tidx % len(_MTS_TARGETS)]\n"
    "                _mts_phase = 'approach'\n"
    "                _mts_count = 0\n"
    "                self._pipeline_context.update({\n"
    "                    '_mts_phase': _mts_phase, '_mts_tidx': _mts_tidx,\n"
    "                    '_mts_count': _mts_count, '_mts_dir_idx': _mts_dir_idx,\n"
    "                })\n"
    "                return 6, {'x': _mts_tx, 'y': _mts_ty}, (\n"
    "                    f'multi_tgt:scan ({_mts_tx},{_mts_ty}) t={_mts_tidx}')\n"
    "            elif _mts_phase == 'approach':\n"
    "                if _mts_count >= _MTS_MOVE_STEPS:\n"
    "                    _mts_phase = 'act'\n"
    "                    _mts_count = 0\n"
    "                _mts_act = _mts_dirs[_mts_dir_idx % len(_mts_dirs)]\n"
    "                if _mts_count % 3 == 0:\n"
    "                    _mts_dir_idx = (_mts_dir_idx + 1) % len(_mts_dirs)\n"
    "                self._pipeline_context.update({\n"
    "                    '_mts_phase': _mts_phase, '_mts_tidx': _mts_tidx,\n"
    "                    '_mts_count': _mts_count, '_mts_dir_idx': _mts_dir_idx,\n"
    "                })\n"
    "                return _mts_act, None, (\n"
    "                    f'multi_tgt:approach A{_mts_act} cnt={_mts_count}')\n"
    "            else:  # act phase\n"
    "                if _mts_count >= _MTS_ACT_COUNT:\n"
    "                    _mts_phase = 'scan'\n"
    "                    _mts_tidx  = (_mts_tidx + 1) % len(_MTS_TARGETS)\n"
    "                    _mts_count = 0\n"
    "                self._pipeline_context.update({\n"
    "                    '_mts_phase': _mts_phase, '_mts_tidx': _mts_tidx,\n"
    "                    '_mts_count': _mts_count, '_mts_dir_idx': _mts_dir_idx,\n"
    "                })\n"
    "                return _mts_commit, None, (\n"
    "                    f'multi_tgt:act A{_mts_commit} cnt={_mts_count}')\n"
    "\n"
    "        elif concept == 'stealth_patrol_wait':\n"
    "            # Observe N frames (wait), then advance briefly, then wait again.\n"
    "            # For stealth games (Splinter Cell, Shadowrun, Metal Gear-style).\n"
    "            # Waits for 'quiet' window (no score_delta threat), then moves.\n"
    "            _SP_WAIT     = 6   # wait steps (observe / commit if safe)\n"
    "            _SP_ADVANCE  = 4   # advance steps when window is clear\n"
    "            _SP_COMMIT_WAIT = 3  # fire commit every N wait steps\n"
    "            if '_sp_phase' not in self._pipeline_context:\n"
    "                self._pipeline_context['_sp_phase']   = 'wait'\n"
    "                self._pipeline_context['_sp_count']   = 0\n"
    "                self._pipeline_context['_sp_dir_idx'] = 0\n"
    "                self._pipeline_context['_sp_steps']   = 0\n"
    "            _sp_phase   = self._pipeline_context['_sp_phase']\n"
    "            _sp_count   = self._pipeline_context['_sp_count']\n"
    "            _sp_dir_idx = self._pipeline_context['_sp_dir_idx']\n"
    "            _sp_steps   = self._pipeline_context['_sp_steps'] + 1\n"
    "            _sp_score   = context.get('score_delta', 0) or 0\n"
    "            _sp_commits = [a for a in avail if a not in {1, 2, 3, 4, 6}]\n"
    "            _sp_dirs    = move_actions or [1, 2, 3, 4]\n"
    "            # If threat detected (negative score), go back to waiting\n"
    "            if _sp_score < -0.05 and _sp_phase == 'advance':\n"
    "                _sp_phase = 'wait'\n"
    "                _sp_count = 0\n"
    "                # Reverse direction\n"
    "                _sp_reverse = {0: 1, 1: 0, 2: 3, 3: 2}\n"
    "                _sp_dir_idx = _sp_reverse.get(_sp_dir_idx % 4, 0)\n"
    "            _sp_count += 1\n"
    "            if _sp_phase == 'wait':\n"
    "                if _sp_count >= _SP_WAIT:\n"
    "                    _sp_phase = 'advance'\n"
    "                    _sp_count = 0\n"
    "                # During wait: fire commit occasionally (check surroundings)\n"
    "                if _sp_commits and _sp_count % _SP_COMMIT_WAIT == 0:\n"
    "                    _sp_act = _sp_commits[0]\n"
    "                else:\n"
    "                    _sp_act = _sp_dirs[_sp_dir_idx % len(_sp_dirs)]  # small sidestep\n"
    "                self._pipeline_context.update({\n"
    "                    '_sp_phase': _sp_phase, '_sp_count': _sp_count,\n"
    "                    '_sp_dir_idx': _sp_dir_idx, '_sp_steps': _sp_steps,\n"
    "                })\n"
    "                return _sp_act, None, (\n"
    "                    f'stealth_wait:wait A{_sp_act} cnt={_sp_count}')\n"
    "            else:  # advance\n"
    "                if _sp_count >= _SP_ADVANCE:\n"
    "                    _sp_phase   = 'wait'\n"
    "                    _sp_count   = 0\n"
    "                    _sp_dir_idx = (_sp_dir_idx + 1) % len(_sp_dirs)\n"
    "                _sp_act = _sp_dirs[_sp_dir_idx % len(_sp_dirs)]\n"
    "                self._pipeline_context.update({\n"
    "                    '_sp_phase': _sp_phase, '_sp_count': _sp_count,\n"
    "                    '_sp_dir_idx': _sp_dir_idx, '_sp_steps': _sp_steps,\n"
    "                })\n"
    "                return _sp_act, None, (\n"
    "                    f'stealth_wait:advance A{_sp_act} cnt={_sp_count}')\n"
    "\n"
)

TARGET = "        # navigation / coverage / traversal_ordering / mixed_movement"

# Add new concepts to LONG_PATH_CONCEPTS
OLD_LONG = (
    "                'random_action', 'interact_seek', 'position_commit', 'momentum_build',\n"
    "     "
)
NEW_LONG = (
    "                'random_action', 'interact_seek', 'position_commit', 'momentum_build',\n"
    "                'terrain_modify', 'pursuit_evade', 'physics_probe', 'dialogue_advance',\n"
    "                'multi_target_sequence', 'stealth_patrol_wait', 'phase_transition_detect',\n"
    "     "
)

# Add terrain_modify + pursuit_evade to interact route
OLD_INTERACT_ROUTE = (
    "            cands = ['interact_seek', 'shoot_and_move', 'position_commit',\n"
    "                     'momentum_build', 'dodge_reactive'] + cands"
)
NEW_INTERACT_ROUTE = (
    "            cands = ['interact_seek', 'shoot_and_move', 'position_commit',\n"
    "                     'momentum_build', 'dodge_reactive', 'terrain_modify',\n"
    "                     'multi_target_sequence'] + cands"
)

# Add physics_probe + stealth_patrol_wait to maze priority
OLD_MAZE_PRIO = (
    "            _maze_prio = ['greedy_productive', 'directional_sweep',\n"
    "                          'wall_follower', 'momentum_probe', 'oscillation_escape',\n"
    "                          'gravity_platformer', 'racing_steer', 'physics_probe']"
)
NEW_MAZE_PRIO = (
    "            _maze_prio = ['greedy_productive', 'directional_sweep',\n"
    "                          'wall_follower', 'momentum_probe', 'oscillation_escape',\n"
    "                          'gravity_platformer', 'racing_steer', 'physics_probe',\n"
    "                          'stealth_patrol_wait', 'phase_transition_detect']"
)

with open('bittertruth_ai_upload/competition_notebook_v2.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

cell = nb['cells'][11]
src = ''.join(cell.get('source', []))

assert TARGET in src, 'TARGET not found!'
assert OLD_LONG in src, f'OLD_LONG not found! snippet: {repr(OLD_LONG[:60])}'
assert OLD_INTERACT_ROUTE in src, f'OLD_INTERACT_ROUTE not found!'
assert OLD_MAZE_PRIO in src, f'OLD_MAZE_PRIO not found!'

src2 = src.replace(TARGET, NEW_CONCEPTS + TARGET, 1)
src2 = src2.replace(OLD_LONG, NEW_LONG, 1)
src2 = src2.replace(OLD_INTERACT_ROUTE, NEW_INTERACT_ROUTE, 1)
src2 = src2.replace(OLD_MAZE_PRIO, NEW_MAZE_PRIO, 1)

assert src2 != src
print(f'Added {len(src2) - len(src)} chars')

nb['cells'][11]['source'] = [src2]

src10 = ''.join(nb['cells'][10].get('source', []))
src10_new = src10.replace("_SOLVER_VERSION = 'v83.0'", "_SOLVER_VERSION = 'v84.0'")
assert src10_new != src10
nb['cells'][10]['source'] = [src10_new]

with open('bittertruth_ai_upload/competition_notebook_v2.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f)
print('Done v84')
