-- ============================================================================
-- BitterTruth-AI Ouroboros System - Complete Database Schema
-- ============================================================================
-- 
-- Last Updated: 2025-11-19 21:38:11
-- Auto-generated by export_schema.py
-- 
-- Rule 2 Compliance: All data stored in SQLite database (core_data.db)
-- No file-based logging or persistence
-- ============================================================================

-- Total Tables: 77

-- action_bias_events
CREATE TABLE action_bias_events (
        bias_id TEXT PRIMARY KEY,
        agent_id TEXT NOT NULL,
        game_id TEXT NOT NULL,
        generation INTEGER NOT NULL,
        
        -- Action context
        action_taken INTEGER NOT NULL, -- 1-7
        navigation_state REAL NOT NULL,
        sensation_bias REAL NOT NULL, -- How much sensation influenced this action
        
        -- Outcome tracking
        action_success BOOLEAN DEFAULT NULL,
        score_change INTEGER DEFAULT 0,
        emotional_reward REAL DEFAULT 0.0, -- Internal satisfaction from action
        
        -- Learning impact
        bias_adjustment REAL DEFAULT 0.0, -- How much bias changed due to outcome
        
        -- Timestamp
        bias_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
        
        FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
    );

-- action_effectiveness
CREATE TABLE action_effectiveness (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    game_id TEXT NOT NULL,
    action_number INTEGER NOT NULL,
    attempts INTEGER DEFAULT 0,
    successes INTEGER DEFAULT 0,
    success_rate REAL DEFAULT 0.0,
    avg_score_impact REAL DEFAULT 0.0,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- action_traces
CREATE TABLE action_traces (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL,
    game_id TEXT NOT NULL,
    action_number INTEGER DEFAULT 0, -- Allow 0 for unknown actions
    coordinates TEXT, -- JSON coordinates for Action 6
    timestamp TIMESTAMP NOT NULL,
    frame_before TEXT, -- JSON frame data
    frame_after TEXT, -- JSON frame data
    frame_changed BOOLEAN DEFAULT FALSE,
    score_before REAL DEFAULT 0.0,
    score_after REAL DEFAULT 0.0,
    score_change REAL DEFAULT 0.0,
    response_data TEXT, -- JSON API response
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, level_number INTEGER DEFAULT 1,
    FOREIGN KEY (session_id) REFERENCES training_sessions(session_id)
);

-- agent_agi_metrics
CREATE TABLE agent_agi_metrics (
    agent_id TEXT PRIMARY KEY,
    generation INTEGER NOT NULL,
    
    -- Diversity metrics
    unique_games_played INTEGER DEFAULT 0,
    unique_games_scored INTEGER DEFAULT 0,      -- Games with ANY score > 0
    game_diversity_ratio REAL DEFAULT 0.0,      -- scored/played ratio
    
    -- Generalization metrics
    novel_game_performance REAL DEFAULT 0.0,    -- Avg score on first-time games
    novel_games_attempted INTEGER DEFAULT 0,
    novel_games_scored INTEGER DEFAULT 0,
    
    -- Few-shot learning metrics
    few_shot_improvement_avg REAL DEFAULT 0.0,  -- Avg improvement attempt 1â†’2
    few_shot_success_rate REAL DEFAULT 0.0,     -- % games improved on 2nd try
    
    -- Anti-overfitting metrics
    max_repeats_on_single_game INTEGER DEFAULT 0,
    overfitting_penalty REAL DEFAULT 0.0,       -- Penalty if too focused on one game
    
    -- AGI fitness score (50% novel + 30% few-shot + 20% diversity)
    agi_fitness_score REAL DEFAULT 0.0,
    
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
);

-- agent_arc_performance
CREATE TABLE agent_arc_performance (
    performance_id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL,
    game_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    game_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Game results (ARC-native rewards)
    final_score REAL NOT NULL,
    win_score_threshold REAL NOT NULL,
    win_achieved BOOLEAN NOT NULL,
    total_actions INTEGER NOT NULL,
    game_duration_seconds REAL,

    -- Performance metrics
    score_efficiency REAL NOT NULL,        -- score per action
    win_proximity REAL NOT NULL,           -- score / win_score
    level_progressions INTEGER DEFAULT 0,
    action_effectiveness REAL,

    -- Strategy tracking
    strategy_used TEXT NOT NULL,
    genome_config TEXT NOT NULL,           -- JSON genome at time of game
    action_sequence TEXT,                  -- JSON sequence of actions taken

    -- Reward calculation (evolutionary fitness)
    base_reward REAL NOT NULL,
    win_bonus REAL DEFAULT 0.0,
    efficiency_bonus REAL DEFAULT 0.0,
    level_progression_bonus REAL DEFAULT 0.0,
    total_evolutionary_reward REAL NOT NULL, actions_earned INTEGER DEFAULT 0, actions_spent INTEGER DEFAULT 0, action_efficiency REAL DEFAULT 0.0, budget_utilization REAL DEFAULT 0.0,

    FOREIGN KEY (agent_id) REFERENCES agents(agent_id),
    FOREIGN KEY (session_id) REFERENCES training_sessions(session_id)
);

-- agent_discoveries
CREATE TABLE agent_discoveries (discovery_id TEXT PRIMARY KEY, agent_id TEXT NOT NULL, discovery_type TEXT NOT NULL, discovery_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP, sequence_id TEXT, pattern_id TEXT, times_used_by_others INTEGER DEFAULT 0, success_rate_by_others REAL DEFAULT 0.0, innovation_value REAL DEFAULT 0.0, network_enrichment_score REAL DEFAULT 0.0, citations INTEGER DEFAULT 0, prestige_contribution REAL DEFAULT 0.0, generations_persisted INTEGER DEFAULT 0, rule_id TEXT, FOREIGN KEY (agent_id) REFERENCES agents(agent_id));

-- agent_frustration_states
CREATE TABLE agent_frustration_states (
                    agent_id TEXT PRIMARY KEY,
                    generation INTEGER NOT NULL,
                    
                    -- Frustration metrics
                    is_frustrated BOOLEAN DEFAULT FALSE,
                    frustration_level REAL DEFAULT 0.0,  -- 0.0 to 1.0
                    games_without_progress INTEGER DEFAULT 0,
                    consecutive_failures INTEGER DEFAULT 0,
                    action_diversity_score REAL DEFAULT 1.0,  -- 1.0=diverse, 0.0=repetitive
                    
                    -- Frustration triggers
                    stuck_on_game_id TEXT,
                    last_score_improvement REAL DEFAULT 0.0,
                    games_since_improvement INTEGER DEFAULT 0,
                    
                    -- Timestamps
                    became_frustrated_at TIMESTAMP,
                    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    
                    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
                );

-- agent_game_diversity
CREATE TABLE agent_game_diversity (
    agent_id TEXT NOT NULL,
    game_id TEXT NOT NULL,
    attempts INTEGER DEFAULT 0,
    first_attempt_score REAL DEFAULT 0.0,
    best_score REAL DEFAULT 0.0,
    last_attempt_score REAL DEFAULT 0.0,
    is_novel_game BOOLEAN DEFAULT TRUE,        -- First time this agent saw this game
    few_shot_improvement REAL DEFAULT 0.0,     -- Score improvement from attempt 1 to 2
    last_played TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (agent_id, game_id),
    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
);

-- agent_meta_learning
CREATE TABLE agent_meta_learning (
    agent_id TEXT PRIMARY KEY,
    generation INTEGER NOT NULL,
    
    -- Rule acquisition
    total_rules_learned INTEGER DEFAULT 0,
    rules_created_this_gen INTEGER DEFAULT 0,
    avg_rules_per_game REAL DEFAULT 0.0,
    
    -- Transfer learning
    successful_transfers INTEGER DEFAULT 0,
    failed_transfers INTEGER DEFAULT 0,
    transfer_success_rate REAL DEFAULT 0.0,
    
    -- Generalization capability
    avg_rule_generality REAL DEFAULT 0.0,  -- Avg games each rule works on
    novel_game_success_rate REAL DEFAULT 0.0,
    learning_rate REAL DEFAULT 0.0,        -- How fast agent learns new rules
    
    -- Meta-fitness (30% of total fitness in diversity mode)
    meta_fitness_score REAL DEFAULT 0.0,
    
    -- Visual reasoning capability
    visual_primitives_learned INTEGER DEFAULT 0,
    visual_understanding_score REAL DEFAULT 0.0,
    
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
);

-- agent_operating_modes
CREATE TABLE agent_operating_modes (
                mode_id TEXT PRIMARY KEY,
                agent_id TEXT NOT NULL,
                game_id TEXT,
                generation INTEGER NOT NULL,
                assigned_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                
                -- Mode assignment
                operating_mode TEXT NOT NULL,  -- 'pioneer', 'optimizer', 'generalist'
                mode_reason TEXT NOT NULL,      -- Why this mode was assigned
                
                -- Mode parameters applied
                mutation_multiplier REAL NOT NULL,
                action_diversity REAL NOT NULL,
                novelty_seeking REAL NOT NULL,
                
                -- Performance tracking
                actions_taken INTEGER DEFAULT 0,
                score_achieved REAL DEFAULT 0.0,
                win_achieved BOOLEAN DEFAULT FALSE,
                mode_effectiveness REAL DEFAULT 0.5,  -- How well this mode worked for this agent
                
                FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
            );

-- agent_pariah_awareness
CREATE TABLE agent_pariah_awareness (
    agent_id TEXT NOT NULL,
    pariah_id TEXT NOT NULL,
    
    -- Awareness details
    awareness_generation INTEGER NOT NULL,
    awareness_source TEXT NOT NULL,  -- 'self_discovery', 'horizontal_transfer', 'inheritance'
    learned_from_agent TEXT,  -- If learned from another agent
    
    -- Awareness strength
    awareness_level REAL DEFAULT 0.5,  -- 0-1, how well does agent recognize this?
    avoidance_priority REAL DEFAULT 0.5,  -- 0-1, how strongly to avoid?
    
    -- Agent response to pariah
    avoidance_success_count INTEGER DEFAULT 0,  -- Times agent avoided this
    trigger_count INTEGER DEFAULT 0,  -- Times agent fell into trap despite awareness
    total_encounters INTEGER DEFAULT 0,
    avg_score_saved REAL DEFAULT 0.0,  -- Score saved by avoiding
    
    -- Awareness lifecycle
    is_active BOOLEAN DEFAULT TRUE,
    last_encountered_generation INTEGER,
    false_positive_count INTEGER DEFAULT 0,  -- Times avoided when shouldn't have
    
    PRIMARY KEY (agent_id, pariah_id),
    FOREIGN KEY (agent_id) REFERENCES agents(agent_id),
    FOREIGN KEY (pariah_id) REFERENCES pariahs(pariah_id),
    FOREIGN KEY (learned_from_agent) REFERENCES agents(agent_id)
);

-- agent_performance_history
CREATE TABLE agent_performance_history (
    history_id INTEGER PRIMARY KEY AUTOINCREMENT,
    agent_id TEXT NOT NULL,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Performance metrics
    games_played INTEGER DEFAULT 0,
    total_score REAL DEFAULT 0.0,
    avg_score REAL DEFAULT 0.0,
    best_score REAL DEFAULT 0.0,
    worst_score REAL DEFAULT 0.0,
    
    -- Level completion metrics
    total_levels_completed INTEGER DEFAULT 0,
    avg_levels_per_game REAL DEFAULT 0.0,
    
    -- Efficiency metrics
    total_actions INTEGER DEFAULT 0,
    avg_actions_per_game REAL DEFAULT 0.0,
    avg_efficiency REAL DEFAULT 0.0,  -- score / actions
    
    -- Win rate
    wins INTEGER DEFAULT 0,
    win_rate REAL DEFAULT 0.0,
    
    -- Sequence contribution
    sequences_discovered INTEGER DEFAULT 0,
    sequences_validated INTEGER DEFAULT 0,
    
    -- Prestige snapshot
    prestige_score REAL DEFAULT 0.0,
    
    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
);

-- agent_signal_responses
CREATE TABLE agent_signal_responses (
        response_id TEXT PRIMARY KEY,
        agent_id TEXT NOT NULL,
        signal_id TEXT NOT NULL,
        response_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        generation INTEGER NOT NULL,
        response_type TEXT NOT NULL,
        response_strength REAL NOT NULL DEFAULT 1.0,
        agent_performance_percentile REAL,
        agent_stress_level REAL DEFAULT 0.5,
        agent_recent_success BOOLEAN DEFAULT FALSE,
        local_diversity REAL DEFAULT 0.0,
        viral_infection_count INTEGER DEFAULT 0,
        pariah_awareness_count INTEGER DEFAULT 0,
        predicted_benefit REAL DEFAULT 0.0,
        actual_impact REAL DEFAULT 0.0,
        FOREIGN KEY (agent_id) REFERENCES agents(agent_id),
        FOREIGN KEY (signal_id) REFERENCES network_regulatory_signals(signal_id),
        UNIQUE(agent_id, signal_id)
    );

-- agent_validation_performance
CREATE TABLE agent_validation_performance (agent_id TEXT PRIMARY KEY, sequences_attempted INTEGER DEFAULT 0, sequences_succeeded INTEGER DEFAULT 0, validation_success_rate REAL DEFAULT 0.0, avg_efficiency_vs_original REAL DEFAULT 1.0, improvement_contributions INTEGER DEFAULT 0, teaching_events INTEGER DEFAULT 0, learning_events INTEGER DEFAULT 0, FOREIGN KEY (agent_id) REFERENCES agents(agent_id));

-- agent_viral_infections
CREATE TABLE agent_viral_infections (
    agent_id TEXT NOT NULL,
    package_id TEXT NOT NULL,
    
    -- Infection details
    infection_generation INTEGER NOT NULL,
    infection_source TEXT NOT NULL,  -- 'discovery', 'horizontal_transfer', 'inheritance', 'mutation'
    infected_by_agent TEXT,  -- If horizontal transfer, who spread it?
    
    -- Infection strength (how much does host express this?)
    infection_strength REAL DEFAULT 0.5,  -- 0-1, affects action selection weight
    expression_level REAL DEFAULT 0.5,  -- 0-1, how actively is host using this?
    
    -- Host response to infection
    success_count INTEGER DEFAULT 0,  -- Times this package helped host
    failure_count INTEGER DEFAULT 0,  -- Times this package failed host
    total_uses INTEGER DEFAULT 0,
    avg_score_boost REAL DEFAULT 0.0,  -- Average score change when using
    
    -- Infection lifecycle
    is_active BOOLEAN DEFAULT TRUE,
    last_used_generation INTEGER,
    immunity_developed BOOLEAN DEFAULT FALSE,  -- Host rejected this package?
    
    PRIMARY KEY (agent_id, package_id),
    FOREIGN KEY (agent_id) REFERENCES agents(agent_id),
    FOREIGN KEY (package_id) REFERENCES viral_information_packages(package_id),
    FOREIGN KEY (infected_by_agent) REFERENCES agents(agent_id)
);

-- agents
CREATE TABLE agents (
    agent_id TEXT PRIMARY KEY,
    agent_type TEXT NOT NULL,
    genome TEXT NOT NULL,              -- JSON strategy parameters
    generation INTEGER NOT NULL,
    parent_ids TEXT,                   -- JSON array of parent agent IDs
    specialization TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- ARC performance metrics (ARC-native rewards)
    total_games_played INTEGER DEFAULT 0,
    total_games_won INTEGER DEFAULT 0,
    total_score_achieved REAL DEFAULT 0.0,
    avg_score_per_game REAL DEFAULT 0.0,
    best_single_game_score REAL DEFAULT 0.0,
    avg_actions_per_game REAL DEFAULT 0.0,
    score_efficiency REAL DEFAULT 0.0,
    level_progressions_detected INTEGER DEFAULT 0,

    -- Evolution tracking
    mutation_count INTEGER DEFAULT 0,
    crossover_count INTEGER DEFAULT 0,
    last_performance_update TIMESTAMP,

    -- Status
    is_active BOOLEAN DEFAULT TRUE,
    retirement_reason TEXT
, epigenetics TEXT, discovery_prestige REAL DEFAULT 0.0, innovation_score REAL DEFAULT 0.0, sequence_discovery_count INTEGER DEFAULT 0, pattern_discovery_count INTEGER DEFAULT 0, validation_reputation REAL DEFAULT 0.5, breeding_priority REAL DEFAULT 1.0, survival_protection REAL DEFAULT 0.0, bonus_game_slots INTEGER DEFAULT 0, action_allowance_per_level INTEGER DEFAULT 400, action_allowance_total INTEGER DEFAULT 7000, action_budget_multiplier REAL DEFAULT 1.0, last_salary_adjustment_gen INTEGER DEFAULT 0, recombination_discoveries INTEGER DEFAULT 0, successful_recombinations INTEGER DEFAULT 0, recombination_success_rate REAL DEFAULT 0.0, sensation_profile TEXT DEFAULT '{}', navigation_state REAL DEFAULT 0.0, action_biases TEXT DEFAULT '{}', sensation_learning_rate REAL DEFAULT 0.3, state_update_sensitivity REAL DEFAULT 0.7, emotional_intelligence_score REAL DEFAULT 0.0, last_prestige_update_gen INTEGER DEFAULT 0, social_rule_adherence REAL DEFAULT 0.5);

-- analytics_snapshots
CREATE TABLE analytics_snapshots (
            snapshot_id INTEGER PRIMARY KEY AUTOINCREMENT,
            snapshot_type TEXT,
            data TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

-- arc_action_tracking
CREATE TABLE arc_action_tracking (
    action_id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL,
    game_id TEXT NOT NULL,
    action_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Action details
    action_type TEXT NOT NULL,
    action_data TEXT NOT NULL,             -- JSON action parameters
    coordinate_x INTEGER,                  -- For ACTION6 tracking (0-63 range)
    coordinate_y INTEGER,                  -- For ACTION6 tracking (0-63 range)

    -- API verification (Rule 7: Verify real actions sent to ARC games)
    api_request_sent BOOLEAN NOT NULL,
    api_response_received BOOLEAN NOT NULL,
    api_response_data TEXT,                -- JSON API response

    -- Effectiveness tracking
    score_before_action REAL,
    score_after_action REAL,
    score_delta REAL,
    immediate_reward REAL,

    -- Validation
    coordinate_valid BOOLEAN,              -- Within 0-63 range check
    action_accepted BOOLEAN,               -- ARC API accepted action
    error_message TEXT,

    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
);

-- claude_evolution_decisions
CREATE TABLE claude_evolution_decisions (
    decision_id TEXT PRIMARY KEY,
    generation INTEGER NOT NULL,
    decision_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Claude Code analysis
    population_analysis TEXT NOT NULL,      -- JSON analysis results
    evolution_strategy TEXT NOT NULL,       -- JSON strategy decisions
    reasoning TEXT NOT NULL,                -- Claude's reasoning for decisions

    -- Execution results
    agents_created INTEGER DEFAULT 0,
    agents_retired INTEGER DEFAULT 0,
    mutations_applied INTEGER DEFAULT 0,
    crossovers_performed INTEGER DEFAULT 0,

    -- Performance expectations
    expected_improvement_rate REAL,
    target_win_rate REAL,
    strategy_focus TEXT,                    -- 'exploration', 'exploitation', 'diversification'

    -- Results tracking
    actual_improvement_rate REAL,
    success_indicator BOOLEAN,
    notes TEXT
);

-- claude_memory
CREATE TABLE claude_memory (
    memory_id TEXT PRIMARY KEY,
    memory_type TEXT NOT NULL,             -- 'successful_strategy', 'failed_approach', 'pattern_discovery'
    content TEXT NOT NULL,                 -- JSON memory content
    relevance_score REAL DEFAULT 1.0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_accessed TIMESTAMP,
    access_count INTEGER DEFAULT 0,

    -- Memory linking
    related_agents TEXT,                   -- JSON array of related agent IDs
    related_decisions TEXT,                -- JSON array of related decision IDs
    context_tags TEXT,                     -- JSON array of context tags

    -- Memory validation
    validation_status TEXT DEFAULT 'unverified',  -- 'verified', 'contradicted', 'unverified'
    validation_evidence TEXT              -- JSON evidence for/against memory
);

-- collective_action_proposals
CREATE TABLE collective_action_proposals (
                    proposal_id TEXT PRIMARY KEY,
                    session_id TEXT NOT NULL,
                    turn_number INTEGER NOT NULL,
                    proposing_agent_id TEXT NOT NULL,
                    
                    -- Proposal details
                    proposed_action INTEGER NOT NULL,  -- ACTION1-7
                    action_coordinates TEXT,  -- JSON: coordinates if ACTION6
                    reasoning TEXT NOT NULL,  -- Why this action?
                    confidence REAL DEFAULT 0.5,  -- Agent's confidence in proposal
                    
                    -- Voting results
                    votes_for INTEGER DEFAULT 0,
                    votes_against INTEGER DEFAULT 0,
                    votes_abstain INTEGER DEFAULT 0,
                    proposal_accepted BOOLEAN DEFAULT FALSE,
                    
                    -- Execution results
                    was_executed BOOLEAN DEFAULT FALSE,
                    score_before REAL,
                    score_after REAL,
                    actual_effectiveness REAL,
                    
                    -- Timestamps
                    proposed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    voted_at TIMESTAMP,
                    executed_at TIMESTAMP,
                    
                    FOREIGN KEY (session_id) REFERENCES collective_reasoning_sessions(session_id),
                    FOREIGN KEY (proposing_agent_id) REFERENCES agents(agent_id)
                );

-- collective_insights
CREATE TABLE collective_insights (
                    insight_id TEXT PRIMARY KEY,
                    session_id TEXT NOT NULL,
                    generation INTEGER NOT NULL,
                    
                    -- Insight details
                    insight_type TEXT NOT NULL,  -- 'pattern_recognition', 'strategy_hypothesis', 'failure_prediction'
                    insight_description TEXT NOT NULL,
                    contributing_agents TEXT,  -- JSON: agents who contributed
                    confidence_score REAL DEFAULT 0.5,
                    
                    -- Validation
                    was_correct BOOLEAN,
                    evidence TEXT,  -- JSON: supporting evidence
                    
                    -- Impact
                    actions_influenced INTEGER DEFAULT 0,
                    score_impact REAL DEFAULT 0.0,
                    
                    -- Timestamps
                    emerged_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    validated_at TIMESTAMP,
                    
                    FOREIGN KEY (session_id) REFERENCES collective_reasoning_sessions(session_id)
                );

-- collective_reasoning_sessions
CREATE TABLE collective_reasoning_sessions (
                    session_id TEXT PRIMARY KEY,
                    game_id TEXT NOT NULL,
                    generation INTEGER NOT NULL,
                    
                    -- Participating agents
                    agent_ids TEXT NOT NULL,  -- JSON: list of agent IDs
                    agent_count INTEGER NOT NULL,
                    lead_agent_id TEXT,  -- Coordinator agent
                    
                    -- Session configuration
                    reasoning_mode TEXT NOT NULL,  -- 'voting', 'consensus', 'specialization'
                    consensus_threshold REAL DEFAULT 0.6,
                    
                    -- Session state
                    session_status TEXT DEFAULT 'active',  -- 'active', 'completed', 'failed'
                    current_turn INTEGER DEFAULT 0,
                    total_turns INTEGER DEFAULT 0,
                    
                    -- Performance
                    initial_score REAL DEFAULT 0.0,
                    final_score REAL DEFAULT 0.0,
                    score_improvement REAL DEFAULT 0.0,
                    actions_taken INTEGER DEFAULT 0,
                    
                    -- Collective dynamics
                    consensus_reached_count INTEGER DEFAULT 0,
                    disagreement_count INTEGER DEFAULT 0,
                    avg_confidence REAL DEFAULT 0.0,
                    
                    -- Timestamps
                    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    completed_at TIMESTAMP
                );

-- collective_votes
CREATE TABLE collective_votes (
                    vote_id TEXT PRIMARY KEY,
                    proposal_id TEXT NOT NULL,
                    voting_agent_id TEXT NOT NULL,
                    
                    -- Vote details
                    vote_choice TEXT NOT NULL,  -- 'for', 'against', 'abstain'
                    vote_weight REAL DEFAULT 1.0,  -- Based on agent expertise
                    vote_reasoning TEXT,
                    confidence_in_vote REAL DEFAULT 0.5,
                    
                    -- Timestamps
                    voted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    
                    FOREIGN KEY (proposal_id) REFERENCES collective_action_proposals(proposal_id),
                    FOREIGN KEY (voting_agent_id) REFERENCES agents(agent_id)
                );

-- counterfactual_learnings
CREATE TABLE counterfactual_learnings (
                    learning_id TEXT PRIMARY KEY,
                    agent_id TEXT NOT NULL,
                    generation INTEGER NOT NULL,
                    
                    -- Learning content
                    learning_type TEXT NOT NULL,  -- 'action_preference', 'timing_insight', 'strategy_improvement'
                    learning_description TEXT NOT NULL,
                    supporting_scenarios TEXT,  -- JSON: scenario_ids that support this
                    
                    -- Actionability
                    is_actionable BOOLEAN DEFAULT TRUE,
                    recommended_behavior_change TEXT,  -- JSON: specific changes
                    expected_improvement REAL DEFAULT 0.0,
                    
                    -- Validation
                    times_applied INTEGER DEFAULT 0,
                    success_when_applied INTEGER DEFAULT 0,
                    failure_when_applied INTEGER DEFAULT 0,
                    actual_improvement REAL DEFAULT 0.0,
                    
                    -- Confidence
                    confidence_score REAL DEFAULT 0.5,
                    confidence_source TEXT,  -- 'prediction', 'validation', 'both'
                    
                    -- Timestamps
                    learned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    last_applied TIMESTAMP,
                    last_validated TIMESTAMP,
                    
                    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
                );

-- counterfactual_scenarios
CREATE TABLE counterfactual_scenarios (
                    scenario_id TEXT PRIMARY KEY,
                    agent_id TEXT NOT NULL,
                    game_id TEXT NOT NULL,
                    session_id TEXT NOT NULL,
                    generation INTEGER DEFAULT 0,
                    
                    -- Original game (what actually happened)
                    actual_actions TEXT NOT NULL,  -- JSON: actual action sequence
                    actual_score REAL NOT NULL,
                    actual_outcome TEXT NOT NULL,  -- 'failed', 'partial'
                    
                    -- Decision point (where things could have changed)
                    decision_point_index INTEGER NOT NULL,  -- Action index where divergence starts
                    decision_point_score REAL NOT NULL,
                    decision_point_context TEXT,  -- JSON: game state at decision point
                    
                    -- Counterfactual (what if?)
                    counterfactual_type TEXT NOT NULL,  -- 'action_substitution', 'timing_variation', 'strategy_shift'
                    alternative_actions TEXT NOT NULL,  -- JSON: alternative action sequence
                    divergence_reason TEXT NOT NULL,  -- Why this alternative?
                    
                    -- Predicted outcome
                    predicted_score REAL,
                    predicted_outcome TEXT,  -- 'likely_win', 'likely_improve', 'likely_same', 'likely_worse'
                    confidence_in_prediction REAL DEFAULT 0.5,
                    
                    -- Validation (if tested)
                    was_tested BOOLEAN DEFAULT FALSE,
                    actual_test_score REAL,
                    prediction_accuracy REAL,
                    
                    -- Learning value
                    learning_value REAL DEFAULT 0.5,  -- How valuable is this counterfactual?
                    priority REAL DEFAULT 0.5,  -- Should this be tested?
                    
                    -- Timestamps
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    tested_at TIMESTAMP,
                    
                    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
                );

-- curriculum_progress
CREATE TABLE curriculum_progress (
    agent_id TEXT NOT NULL,
    stage_number INTEGER NOT NULL,         -- 1: specialization, 2: near_transfer, 3: diversification, 4: generalization
    stage_name TEXT NOT NULL,
    entered_stage TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    exited_stage TIMESTAMP,
    
    -- Stage requirements
    required_win_rate REAL NOT NULL,
    achieved_win_rate REAL DEFAULT 0.0,
    required_transfer_rate REAL,
    achieved_transfer_rate REAL DEFAULT 0.0,
    
    -- Stage performance
    games_played_in_stage INTEGER DEFAULT 0,
    games_won_in_stage INTEGER DEFAULT 0,
    rules_learned_in_stage INTEGER DEFAULT 0,
    successful_transfers_in_stage INTEGER DEFAULT 0,
    
    -- Advancement
    stage_completed BOOLEAN DEFAULT FALSE,
    completion_timestamp TIMESTAMP,
    
    PRIMARY KEY (agent_id, stage_number),
    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
);

-- decision_points
CREATE TABLE decision_points (
                    decision_point_id TEXT PRIMARY KEY,
                    agent_id TEXT NOT NULL,
                    game_id TEXT NOT NULL,
                    
                    -- Decision context
                    action_index INTEGER NOT NULL,
                    score_at_decision REAL NOT NULL,
                    available_actions TEXT,  -- JSON: actions that were available
                    action_taken INTEGER NOT NULL,  -- What agent actually did
                    
                    -- Why is this a decision point?
                    importance_score REAL NOT NULL,  -- How critical was this moment?
                    importance_factors TEXT,  -- JSON: why this matters
                    
                    -- Outcomes
                    immediate_score_change REAL DEFAULT 0.0,
                    final_game_outcome TEXT NOT NULL,
                    
                    -- Alternative analysis
                    counterfactuals_generated INTEGER DEFAULT 0,
                    best_alternative_action INTEGER,
                    best_alternative_predicted_score REAL,
                    
                    -- Timestamps
                    identified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    
                    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
                );

-- discovered_patterns
CREATE TABLE discovered_patterns (
    pattern_id TEXT PRIMARY KEY,
    pattern_name TEXT NOT NULL,
    pattern_type TEXT NOT NULL,            -- 'action_sequence', 'coordinate_cluster', 'color_pattern'
    discovered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Pattern definition
    pattern_signature TEXT NOT NULL,       -- JSON: abstract pattern description
    concrete_examples TEXT NOT NULL,       -- JSON: array of sequence_ids that match
    occurrence_count INTEGER DEFAULT 1,
    success_count INTEGER DEFAULT 1,
    
    -- Effectiveness metrics
    success_rate REAL NOT NULL,            -- % of times pattern leads to win
    avg_score_achieved REAL NOT NULL,
    avg_efficiency REAL NOT NULL,
    confidence_score REAL NOT NULL,        -- statistical confidence
    
    -- Application context
    applicable_game_types TEXT,            -- JSON: which game types this works on
    
    -- Learning status
    validation_status TEXT DEFAULT 'hypothesis',  -- 'hypothesis', 'validated', 'invalidated'
    validation_games INTEGER DEFAULT 0,
    last_validated TIMESTAMP
);

-- ecosystem_health_snapshots
CREATE TABLE ecosystem_health_snapshots (
    snapshot_id TEXT PRIMARY KEY,
    snapshot_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    generation INTEGER NOT NULL,
    
    -- Knowledge metrics (the "database as organism")
    total_sequences INTEGER DEFAULT 0,
    total_patterns INTEGER DEFAULT 0,
    total_learned_rules INTEGER DEFAULT 0,
    unique_games_solved INTEGER DEFAULT 0,
    knowledge_diversity_index REAL DEFAULT 0.0,  -- Shannon entropy of pattern distribution
    
    -- Information flow metrics (the "metabolism")
    sequences_created_this_gen INTEGER DEFAULT 0,
    sequences_validated_this_gen INTEGER DEFAULT 0,
    sequences_reused_this_gen INTEGER DEFAULT 0,
    rules_learned_this_gen INTEGER DEFAULT 0,
    rules_transferred_this_gen INTEGER DEFAULT 0,
    knowledge_creation_rate REAL DEFAULT 0.0,  -- New discoveries per agent-game
    validation_rate REAL DEFAULT 0.0,  -- Successful validations / total attempts
    
    -- Resilience metrics (the "immune system")
    critical_sequences_count INTEGER DEFAULT 0,  -- Sequences with >80% reliability
    orphan_sequences_count INTEGER DEFAULT 0,  -- Sequences with 0 validations
    redundancy_index REAL DEFAULT 0.0,  -- Avg validations per sequence
    knowledge_backup_ratio REAL DEFAULT 0.0,  -- % of knowledge with multiple agent carriers
    
    -- Population metrics (temporary expressions)
    active_agents INTEGER DEFAULT 0,
    agent_diversity_index REAL DEFAULT 0.0,
    avg_agent_lifespan_generations REAL DEFAULT 0.0,
    agent_turnover_rate REAL DEFAULT 0.0,
    
    -- Metabolic health indicators
    network_growth_rate REAL DEFAULT 0.0,  -- Knowledge growth vs population growth
    innovation_vs_exploitation REAL DEFAULT 0.5,  -- New vs reused sequences ratio
    transfer_learning_rate REAL DEFAULT 0.0,  -- Successful rule transfers per agent
    system_entropy REAL DEFAULT 0.0,  -- Overall disorder measure
    
    -- Overall health assessment
    health_status TEXT DEFAULT 'unknown',  -- 'critical', 'poor', 'fair', 'good', 'excellent'
    health_score REAL DEFAULT 0.0  -- 0.0 to 1.0
, total_levels_completed_this_gen INTEGER DEFAULT 0, avg_levels_per_game REAL DEFAULT 0.0, avg_actions_per_level REAL DEFAULT 0.0, network_learning_rate REAL DEFAULT 0.0);

-- ecosystem_metabolism_snapshots
CREATE TABLE ecosystem_metabolism_snapshots (
            snapshot_id TEXT PRIMARY KEY,
            generation INTEGER NOT NULL,
            snapshot_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            
            -- Total metabolic capacity (network ATP pool)
            total_actions_available INTEGER NOT NULL,
            total_actions_budgeted INTEGER NOT NULL,
            total_actions_spent INTEGER NOT NULL,
            total_actions_wasted INTEGER NOT NULL,
            
            -- Resource distribution metrics
            gini_coefficient REAL DEFAULT 0.0,
            top_10_percent_share REAL DEFAULT 0.0,
            bottom_50_percent_share REAL DEFAULT 0.0,
            
            -- Metabolic rates (network dynamics)
            action_creation_rate REAL DEFAULT 0.0,
            action_destruction_rate REAL DEFAULT 0.0,
            metabolic_efficiency REAL DEFAULT 0.0,
            
            -- Network health indicators
            resource_scarcity_index REAL DEFAULT 0.0,
            budget_inflation_rate REAL DEFAULT 0.0,
            
            -- Population economics
            active_agent_count INTEGER NOT NULL,
            agents_above_baseline INTEGER DEFAULT 0,
            agents_below_baseline INTEGER DEFAULT 0
        );

-- frustration_quorum_events
CREATE TABLE frustration_quorum_events (
                    event_id TEXT PRIMARY KEY,
                    generation INTEGER NOT NULL,
                    event_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    
                    -- Quorum metrics
                    total_agents INTEGER NOT NULL,
                    frustrated_agents INTEGER NOT NULL,
                    frustration_ratio REAL NOT NULL,
                    quorum_reached BOOLEAN NOT NULL,
                    
                    -- Trigger details
                    desperation_signal_id TEXT,  -- Signal emitted if quorum reached
                    signal_strength REAL,
                    
                    -- Network response
                    parameter_adjustments TEXT,  -- JSON: what changed
                    response_timestamp TIMESTAMP,
                    
                    -- Outcome tracking
                    frustration_resolved BOOLEAN DEFAULT FALSE,
                    resolution_generation INTEGER,
                    improvement_observed REAL DEFAULT 0.0
                );

-- frustration_resolutions
CREATE TABLE frustration_resolutions (
                    resolution_id TEXT PRIMARY KEY,
                    quorum_event_id TEXT NOT NULL,
                    generation INTEGER NOT NULL,
                    
                    -- Strategy applied
                    strategy_type TEXT NOT NULL,  -- 'increase_mutation', 'boost_exploration', 'reset_population', etc.
                    strategy_parameters TEXT NOT NULL,  -- JSON
                    
                    -- Effectiveness
                    agents_affected INTEGER DEFAULT 0,
                    frustration_before REAL NOT NULL,
                    frustration_after REAL,
                    resolution_successful BOOLEAN,
                    
                    -- Timestamps
                    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    measured_at TIMESTAMP,
                    
                    FOREIGN KEY (quorum_event_id) REFERENCES frustration_quorum_events(event_id)
                );

-- game_exposure_history
CREATE TABLE game_exposure_history (
    game_id TEXT NOT NULL,
    generation INTEGER NOT NULL,
    times_played INTEGER DEFAULT 0,
    unique_agents_played INTEGER DEFAULT 0,
    avg_score REAL DEFAULT 0.0,
    best_score REAL DEFAULT 0.0,
    is_retired BOOLEAN DEFAULT FALSE,           -- Retired if played too much
    retirement_reason TEXT,
    last_played TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (game_id, generation)
);

-- game_results
CREATE TABLE game_results (
    game_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    status TEXT NOT NULL, -- 'completed', 'failed', 'timeout', 'cancelled'
    final_score REAL DEFAULT 0.0,
    total_actions INTEGER DEFAULT 0,
    actions_taken TEXT, -- JSON array of action numbers
    available_actions TEXT, -- JSON array of available actions at game start
    win_detected BOOLEAN DEFAULT FALSE,
    level_completions INTEGER DEFAULT 0,
    frame_changes INTEGER DEFAULT 0,
    coordinate_attempts INTEGER DEFAULT 0,
    coordinate_successes INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, scorecard_id TEXT,
    PRIMARY KEY (game_id, session_id),
    FOREIGN KEY (session_id) REFERENCES training_sessions(session_id)
);

-- game_visual_analysis
CREATE TABLE game_visual_analysis (
    analysis_id TEXT PRIMARY KEY,
    game_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    agent_id TEXT NOT NULL,
    frame_number INTEGER NOT NULL,
    analysis_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Frame data
    frame_data TEXT NOT NULL,              -- JSON: the actual frame
    
    -- Visual features (from visual_reasoning_engine)
    symmetry_detected TEXT,                -- JSON: symmetry types and confidence
    patterns_found TEXT,                   -- JSON: repeating patterns
    colors_analyzed TEXT,                  -- JSON: color distribution
    shapes_detected TEXT,                  -- JSON: shape information
    spatial_relations TEXT,                -- JSON: relationships between objects
    complexity_metrics TEXT,               -- JSON: complexity scores
    
    -- Transformation suggestions
    likely_transformations TEXT,           -- JSON: suggested actions based on visual analysis
    
    -- Used for rule learning
    used_in_rule_id TEXT,
    
    FOREIGN KEY (agent_id) REFERENCES agents(agent_id),
    FOREIGN KEY (used_in_rule_id) REFERENCES learned_rules(rule_id)
);

-- global_counters
CREATE TABLE global_counters (
    counter_name TEXT PRIMARY KEY,
    counter_value INTEGER DEFAULT 0,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    description TEXT
);

-- horizontal_transfer_events
CREATE TABLE horizontal_transfer_events (
                transfer_id TEXT PRIMARY KEY,
                donor_agent_id TEXT NOT NULL,
                recipient_agent_id TEXT NOT NULL,
                generation INTEGER NOT NULL,
                
                -- Transfer classification
                transfer_type TEXT NOT NULL,  -- 'layer_1_genome', 'layer_2_epigenetic', 'layer_3_somatic'
                transfer_layer INTEGER NOT NULL,  -- 1, 2, or 3
                
                -- Emotional compatibility (Phase 4.5 enhancement)
                emotional_compatibility REAL NOT NULL,
                success_probability REAL NOT NULL,
                transfer_successful BOOLEAN NOT NULL,
                
                -- Transfer content and results
                knowledge_content TEXT,  -- JSON: what was transferred
                emotional_context TEXT,  -- JSON: emotional state during transfer
                knowledge_transferred BOOLEAN DEFAULT FALSE,
                performance_impact REAL DEFAULT 0.0,  -- Recipient performance change
                
                -- Metadata
                transfer_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                notes TEXT,
                
                FOREIGN KEY (donor_agent_id) REFERENCES agents(agent_id),
                FOREIGN KEY (recipient_agent_id) REFERENCES agents(agent_id)
            );

-- knowledge_graph_edges
CREATE TABLE knowledge_graph_edges (
    edge_id TEXT PRIMARY KEY,
    source_knowledge_id TEXT NOT NULL,
    target_knowledge_id TEXT NOT NULL,
    source_knowledge_type TEXT NOT NULL,  -- 'sequence', 'pattern', 'rule'
    target_knowledge_type TEXT NOT NULL,
    edge_type TEXT NOT NULL,  -- 'builds_on', 'contradicts', 'generalizes', 'specializes'
    
    -- Edge strength
    confidence REAL DEFAULT 0.5,
    evidence_count INTEGER DEFAULT 1,
    
    -- Discovery
    discovered_by_agent TEXT,
    discovered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    discovered_generation INTEGER,
    
    -- Validation
    validated BOOLEAN DEFAULT FALSE,
    validation_count INTEGER DEFAULT 0,
    
    FOREIGN KEY (discovered_by_agent) REFERENCES agents(agent_id)
);

-- knowledge_propagation_chains
CREATE TABLE knowledge_propagation_chains (
                chain_id TEXT PRIMARY KEY,
                origin_agent_id TEXT NOT NULL,
                knowledge_type TEXT NOT NULL,  -- 'sequence', 'sensation_mapping', 'pattern', etc.
                knowledge_identifier TEXT NOT NULL,  -- sequence_id, pattern_id, etc.
                
                -- Chain tracking
                chain_length INTEGER DEFAULT 1,
                current_carriers INTEGER DEFAULT 1,
                max_carriers_reached INTEGER DEFAULT 1,
                
                -- Performance tracking
                avg_performance_improvement REAL DEFAULT 0.0,
                total_games_won_with_knowledge INTEGER DEFAULT 0,
                
                -- Metadata
                chain_start_generation INTEGER NOT NULL,
                last_transfer_generation INTEGER,
                is_active BOOLEAN DEFAULT TRUE,
                
                FOREIGN KEY (origin_agent_id) REFERENCES agents(agent_id)
            );

-- knowledge_redundancy
CREATE TABLE knowledge_redundancy (
    sequence_id TEXT PRIMARY KEY,
    discovery_timestamp TIMESTAMP,
    discovery_generation INTEGER,
    
    -- Backup metrics (how many agents know this)
    agents_who_know INTEGER DEFAULT 1,  -- How many agents have used this successfully
    agent_carriers TEXT,  -- JSON: list of agent IDs who successfully used this
    validation_attempts INTEGER DEFAULT 0,
    successful_validations INTEGER DEFAULT 0,
    
    -- Criticality assessment
    games_solved_by_this INTEGER DEFAULT 0,  -- How many unique games
    alternative_solutions_exist INTEGER DEFAULT 0,  -- Redundancy at game level
    criticality_score REAL DEFAULT 0.0,  -- How critical is this to network survival
    is_viral_core BOOLEAN DEFAULT FALSE,  -- Essential knowledge that must not be lost
    
    -- Persistence tracking
    generations_survived INTEGER DEFAULT 0,  -- How many generations has this knowledge persisted
    last_used_generation INTEGER DEFAULT 0,
    last_used_timestamp TIMESTAMP,
    risk_of_loss REAL DEFAULT 1.0,  -- Probability of being forgotten (0=safe, 1=at risk)
    
    -- Network contribution
    times_taught_to_others INTEGER DEFAULT 0,
    network_enrichment_value REAL DEFAULT 0.0,
    
    FOREIGN KEY (sequence_id) REFERENCES winning_sequences(sequence_id)
);

-- learned_rules
CREATE TABLE learned_rules (
    rule_id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL,
    source_game_id TEXT NOT NULL,          -- Game where rule was learned
    rule_name TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Rule definition
    preconditions TEXT NOT NULL,           -- JSON: visual conditions that must be met
    action_template TEXT NOT NULL,         -- JSON: sequence of actions to take
    expected_outcome TEXT NOT NULL,        -- 'win', 'progress', 'score_increase'
    
    -- Confidence and success tracking
    confidence REAL DEFAULT 0.5,
    success_count INTEGER DEFAULT 0,
    failure_count INTEGER DEFAULT 0,
    success_rate REAL DEFAULT 0.0,         -- success / (success + failure)
    
    -- Transfer learning
    applicable_games TEXT,                 -- JSON: list of game_ids where rule works
    transferred_successfully BOOLEAN DEFAULT 0,
    transfer_attempts INTEGER DEFAULT 0,
    successful_transfers INTEGER DEFAULT 0,
    
    -- Rule characteristics
    visual_signature TEXT,                 -- Compact signature for quick matching
    complexity_level TEXT,                 -- 'simple', 'moderate', 'complex'
    generality_score REAL DEFAULT 0.0,     -- How many games rule works on
    
    last_updated TIMESTAMP,
    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
);

-- navigation_state_history
CREATE TABLE navigation_state_history (
        history_id TEXT PRIMARY KEY,
        agent_id TEXT NOT NULL,
        game_id TEXT NOT NULL,
        generation INTEGER NOT NULL,
        
        -- State tracking
        navigation_state REAL NOT NULL, -- Internal emotional state
        dominant_emotion TEXT, -- 'confident', 'frustrated', 'curious', 'cautious'
        
        -- Context when state was recorded
        game_score INTEGER DEFAULT 0,
        actions_taken INTEGER DEFAULT 0,
        recent_success_rate REAL DEFAULT NULL,
        
        -- State change triggers
        state_change_trigger TEXT, -- What caused this emotional state
        previous_state REAL DEFAULT NULL,
        state_change_magnitude REAL DEFAULT NULL,
        
        -- Timestamp
        state_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
        
        FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
    );

-- near_miss_games
CREATE TABLE near_miss_games (
                    near_miss_id TEXT PRIMARY KEY,
                    agent_id TEXT NOT NULL,
                    game_id TEXT NOT NULL,
                    session_id TEXT NOT NULL,
                    generation INTEGER DEFAULT 0,
                    
                    -- Score details
                    final_score REAL NOT NULL,
                    win_threshold REAL DEFAULT 20.0,
                    score_gap REAL NOT NULL,  -- How many points away from win
                    near_miss_category TEXT NOT NULL,  -- 'near_win', 'strong_partial', 'partial_progress'
                    
                    -- Game execution
                    total_actions INTEGER NOT NULL,
                    actions_sequence TEXT,  -- JSON: action sequence taken
                    coordinates_used TEXT,  -- JSON: coordinates for ACTION6
                    frame_states TEXT,  -- JSON: key frame states during game
                    
                    -- Analysis
                    what_worked TEXT,  -- JSON: successful patterns/actions
                    what_failed TEXT,  -- JSON: failure points
                    missing_elements TEXT,  -- JSON: what was missing for win
                    critical_mistakes TEXT,  -- JSON: identified mistakes
                    
                    -- Recommendations
                    improvement_suggestions TEXT,  -- JSON: specific suggestions
                    estimated_actions_to_win INTEGER,  -- How many more actions might win
                    
                    -- Timestamps
                    analyzed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    
                    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
                );

-- near_miss_insights
CREATE TABLE near_miss_insights (
                    insight_id TEXT PRIMARY KEY,
                    agent_id TEXT NOT NULL,
                    generation INTEGER NOT NULL,
                    
                    -- Insight details
                    insight_type TEXT NOT NULL,  -- 'action_timing', 'coordinate_selection', 'strategy_flaw'
                    insight_description TEXT NOT NULL,
                    supporting_evidence TEXT,  -- JSON: near_miss_ids that support this
                    
                    -- Actionability
                    is_actionable BOOLEAN DEFAULT TRUE,
                    recommended_change TEXT,  -- JSON: specific behavior changes
                    priority REAL DEFAULT 0.5,  -- 0-1, higher = more important
                    
                    -- Validation
                    times_applied INTEGER DEFAULT 0,
                    success_count INTEGER DEFAULT 0,
                    failure_count INTEGER DEFAULT 0,
                    effectiveness_score REAL DEFAULT 0.0,
                    
                    -- Timestamps
                    discovered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    last_applied TIMESTAMP,
                    
                    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
                );

-- near_miss_patterns
CREATE TABLE near_miss_patterns (
                    pattern_id TEXT PRIMARY KEY,
                    pattern_type TEXT NOT NULL,  -- 'action_sequence', 'coordinate_pattern', 'strategy'
                    pattern_description TEXT NOT NULL,
                    
                    -- Pattern details
                    pattern_signature TEXT NOT NULL,  -- JSON: pattern definition
                    game_types_affected TEXT,  -- JSON: which game types show this
                    
                    -- Occurrence
                    occurrence_count INTEGER DEFAULT 1,
                    affected_agents TEXT,  -- JSON: list of agent IDs
                    
                    -- Impact
                    avg_score_when_present REAL DEFAULT 0.0,
                    prevents_completion BOOLEAN DEFAULT FALSE,
                    correction_strategy TEXT,  -- JSON: how to fix this pattern
                    
                    -- Discovery
                    discovered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    is_active BOOLEAN DEFAULT TRUE
                );

-- network_regulation_history
CREATE TABLE network_regulation_history (
        regulation_id TEXT PRIMARY KEY,
        regulation_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        generation INTEGER NOT NULL,
        parameter_name TEXT NOT NULL,
        old_value REAL NOT NULL,
        new_value REAL NOT NULL,
        adjustment_magnitude REAL NOT NULL,
        triggering_signal_id TEXT,
        net_signal_strength REAL NOT NULL,
        signal_consensus_level REAL DEFAULT 0.5,
        predicted_improvement TEXT,
        actual_improvement_measured REAL DEFAULT 0.0,
        regulation_success BOOLEAN,
        network_health_before REAL DEFAULT 0.5,
        network_health_after REAL DEFAULT 0.5,
        failing_metrics_addressed TEXT,
        FOREIGN KEY (triggering_signal_id) REFERENCES network_regulatory_signals(signal_id)
    );

-- network_regulatory_signals
CREATE TABLE network_regulatory_signals (
        signal_id TEXT PRIMARY KEY,
        signal_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        generation INTEGER NOT NULL,
        signal_type TEXT NOT NULL,
        signal_source_agent TEXT,
        initial_strength REAL NOT NULL DEFAULT 1.0,
        current_strength REAL NOT NULL DEFAULT 1.0,
        propagation_radius INTEGER DEFAULT 0,
        target_parameter TEXT NOT NULL,
        adjustment_direction TEXT NOT NULL,
        adjustment_magnitude REAL DEFAULT 0.1,
        decay_rate REAL DEFAULT 0.1,
        expires_generation INTEGER,
        is_active BOOLEAN DEFAULT TRUE,
        agents_responding INTEGER DEFAULT 0,
        net_amplification REAL DEFAULT 0.0,
        effectiveness_score REAL DEFAULT 0.0,
        FOREIGN KEY (signal_source_agent) REFERENCES agents(agent_id)
    );

-- object_sensation_mappings
CREATE TABLE object_sensation_mappings (
        mapping_id TEXT PRIMARY KEY,
        agent_id TEXT NOT NULL,
        generation INTEGER NOT NULL,
        
        -- Object identification
        object_type TEXT NOT NULL,
        object_characteristics TEXT, -- JSON: color, size, pattern, etc.
        
        -- Sensation data
        sensation_score REAL NOT NULL, -- -1.0 to 1.0 (negative=avoid, positive=approach)
        confidence_level REAL DEFAULT 0.5, -- How confident agent is in this sensation
        
        -- Learning context
        learn_count INTEGER DEFAULT 1, -- How many times this sensation was reinforced
        success_count INTEGER DEFAULT 0, -- How many successful outcomes with this sensation
        failure_count INTEGER DEFAULT 0, -- How many failed outcomes with this sensation
        
        -- Timestamps
        first_learned DATETIME DEFAULT CURRENT_TIMESTAMP,
        last_updated DATETIME DEFAULT CURRENT_TIMESTAMP,
        
        FOREIGN KEY (agent_id) REFERENCES agents(agent_id),
        UNIQUE(agent_id, object_type)
    );

-- optimization_status
CREATE TABLE optimization_status (
                status_id TEXT PRIMARY KEY,
                game_id TEXT NOT NULL,
                level_number INTEGER NOT NULL,
                
                -- Optimization metrics
                is_optimized BOOLEAN DEFAULT FALSE,
                best_sequence_id TEXT,
                best_actions INTEGER,
                best_efficiency REAL,
                
                -- Tracking improvement
                last_improvement_generation INTEGER,
                generations_without_improvement INTEGER DEFAULT 0,
                improvement_rate REAL DEFAULT 0.0,  -- % improvement in recent generations
                
                -- Sequence diversity
                total_sequences INTEGER DEFAULT 0,
                active_sequences INTEGER DEFAULT 0,
                
                -- Timestamps
                first_sequence_at TIMESTAMP,
                last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                optimized_at TIMESTAMP,
                
                UNIQUE(game_id, level_number)
            );

-- pariah_package_interactions
CREATE TABLE pariah_package_interactions (
    pariah_id TEXT NOT NULL,
    package_id TEXT NOT NULL,
    
    interaction_type TEXT NOT NULL,  -- 'protective', 'causative', 'neutral'
    interaction_strength REAL DEFAULT 0.0,  -- -1.0 (causes) to +1.0 (protects)
    
    -- Evidence
    co_occurrence_count INTEGER DEFAULT 0,  -- Times package + pariah in same context
    protection_score REAL DEFAULT 0.0,  -- Does package prevent pariah?
    causation_score REAL DEFAULT 0.0,  -- Does package trigger pariah?
    observations INTEGER DEFAULT 0,
    
    PRIMARY KEY (pariah_id, package_id),
    FOREIGN KEY (pariah_id) REFERENCES pariahs(pariah_id),
    FOREIGN KEY (package_id) REFERENCES viral_information_packages(package_id)
);

-- pariahs
CREATE TABLE pariahs (
    pariah_id TEXT PRIMARY KEY,
    pariah_name TEXT NOT NULL,
    pariah_type TEXT NOT NULL,  -- 'action_sequence', 'coordinate_trap', 'strategy_failure'
    
    -- Failure pattern (what should agents avoid?)
    action_sequence TEXT,  -- JSON array - this sequence leads to failure
    coordinate_pattern TEXT,  -- JSON array - these coordinates are traps
    failure_description TEXT,  -- Why does this fail?
    
    -- Pariah characteristics
    toxicity REAL DEFAULT 0.5,  -- How harmful is this pattern? (0-1)
    detection_difficulty REAL DEFAULT 0.3,  -- How hard to recognize? (0-1)
    context_specificity REAL DEFAULT 0.5,  -- Game-specific or universal? (0-1)
    
    -- Pariah impact (network-level damage)
    trigger_count INTEGER DEFAULT 0,  -- Times agents fell into this trap
    avg_score_loss REAL DEFAULT 0.0,  -- Average score lost when triggered
    total_awareness INTEGER DEFAULT 0,  -- How many agents know this?
    active_awareness INTEGER DEFAULT 0,  -- How many actively avoid this?
    
    -- Origins
    discovery_generation INTEGER NOT NULL,
    source_game_id TEXT,  -- Game where this failure was discovered
    source_agent_id TEXT,  -- Agent who discovered (failed)
    parent_pariah_id TEXT,  -- If this is a variant of another failure
    
    -- Lifecycle
    is_active BOOLEAN DEFAULT TRUE,
    obsolescence_score REAL DEFAULT 0.0,  -- Is this pariah no longer relevant?
    last_triggered_generation INTEGER,
    avoidance_success_rate REAL DEFAULT 0.0,  -- % of aware agents who avoid
    
    FOREIGN KEY (source_agent_id) REFERENCES agents(agent_id),
    FOREIGN KEY (parent_pariah_id) REFERENCES pariahs(pariah_id)
);

-- pattern_applications
CREATE TABLE pattern_applications (
    application_id TEXT PRIMARY KEY,
    pattern_id TEXT NOT NULL,
    sequence_id TEXT,
    game_id TEXT NOT NULL,
    agent_id TEXT NOT NULL,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Results
    success BOOLEAN NOT NULL,
    score_achieved REAL NOT NULL,
    actions_taken INTEGER NOT NULL,
    
    FOREIGN KEY (pattern_id) REFERENCES discovered_patterns(pattern_id),
    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
);

-- pattern_synthesis
CREATE TABLE pattern_synthesis (
            synthesis_id TEXT PRIMARY KEY,
            pattern_a_id TEXT NOT NULL,
            pattern_b_id TEXT NOT NULL,
            synthesized_pattern_id TEXT NOT NULL,
            
            novelty_score REAL DEFAULT 0.0,
            effectiveness_score REAL DEFAULT 0.0,
            games_applied_to INTEGER DEFAULT 0,
            success_count INTEGER DEFAULT 0,
            
            discovery_agent_id TEXT,
            discovery_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            discovery_generation INTEGER DEFAULT 0,
            
            times_recombined INTEGER DEFAULT 0,
            descendant_count INTEGER DEFAULT 0,
            
            FOREIGN KEY (pattern_a_id) REFERENCES discovered_patterns(pattern_id),
            FOREIGN KEY (pattern_b_id) REFERENCES discovered_patterns(pattern_id),
            FOREIGN KEY (synthesized_pattern_id) REFERENCES discovered_patterns(pattern_id),
            FOREIGN KEY (discovery_agent_id) REFERENCES agents(agent_id)
        );

-- population_health_metrics
CREATE TABLE population_health_metrics (
    metric_id TEXT PRIMARY KEY,
    generation INTEGER NOT NULL,
    measurement_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Diversity measurements
    genetic_diversity_score REAL NOT NULL,
    strategy_distribution TEXT NOT NULL,    -- JSON distribution of agent types
    performance_variance REAL NOT NULL,

    -- Health indicators
    stagnation_indicator REAL NOT NULL,
    improvement_rate REAL NOT NULL,
    population_size INTEGER NOT NULL,
    active_agents INTEGER NOT NULL,

    -- Performance benchmarks
    best_win_rate REAL NOT NULL,
    average_win_rate REAL NOT NULL,
    worst_win_rate REAL NOT NULL,
    win_rate_std_dev REAL NOT NULL,

    -- Strategic analysis
    dominant_strategies TEXT,              -- JSON list of most successful strategies
    emerging_patterns TEXT,                -- JSON patterns Claude Code has identified
    recommendations TEXT                   -- JSON Claude Code recommendations
);

-- recombination_attempts
CREATE TABLE recombination_attempts (
            attempt_id TEXT PRIMARY KEY,
            agent_id TEXT NOT NULL,
            game_id TEXT NOT NULL,
            attempt_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            generation INTEGER NOT NULL,
            
            sequence_a_id TEXT NOT NULL,
            sequence_b_id TEXT NOT NULL,
            combination_type TEXT NOT NULL CHECK(combination_type IN ('chain', 'interleave', 'conditional')),
            
            was_successful BOOLEAN NOT NULL,
            resulting_sequence_id TEXT,
            resulting_score INTEGER DEFAULT 0,
            actions_used INTEGER DEFAULT 0,
            
            failure_reason TEXT,
            
            FOREIGN KEY (agent_id) REFERENCES agents(agent_id),
            FOREIGN KEY (game_id) REFERENCES game_results(game_id),
            FOREIGN KEY (sequence_a_id) REFERENCES winning_sequences(sequence_id),
            FOREIGN KEY (sequence_b_id) REFERENCES winning_sequences(sequence_id),
            FOREIGN KEY (resulting_sequence_id) REFERENCES winning_sequences(sequence_id)
        );

-- rule_redundancy
CREATE TABLE rule_redundancy (
    rule_id TEXT PRIMARY KEY,
    discovery_timestamp TIMESTAMP,
    discovery_generation INTEGER,
    
    -- Backup metrics
    agents_who_discovered INTEGER DEFAULT 1,
    agent_carriers TEXT,  -- JSON: list of agent IDs who independently discovered this
    independent_discoveries INTEGER DEFAULT 1,
    
    -- Criticality for network
    games_applicable_to INTEGER DEFAULT 0,
    transfer_success_count INTEGER DEFAULT 0,
    criticality_score REAL DEFAULT 0.0,
    is_viral_core BOOLEAN DEFAULT FALSE,
    
    -- Persistence
    generations_survived INTEGER DEFAULT 0,
    last_used_generation INTEGER DEFAULT 0,
    risk_of_loss REAL DEFAULT 1.0,
    
    FOREIGN KEY (rule_id) REFERENCES learned_rules(rule_id)
);

-- rule_transfers
CREATE TABLE rule_transfers (
    transfer_id TEXT PRIMARY KEY,
    rule_id TEXT NOT NULL,
    source_game_id TEXT NOT NULL,
    target_game_id TEXT NOT NULL,
    agent_id TEXT NOT NULL,
    transfer_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Transfer results
    transfer_successful BOOLEAN NOT NULL,
    confidence_before REAL NOT NULL,
    confidence_after REAL,
    score_achieved REAL,
    actions_taken INTEGER,
    
    -- Analysis
    match_confidence REAL,                 -- How well preconditions matched
    execution_quality REAL,                -- How well actions were executed
    actual_result TEXT,                    -- 'full_win', 'partial_success', 'no_progress', 'failure'
    failure_reason TEXT,
    
    FOREIGN KEY (rule_id) REFERENCES learned_rules(rule_id),
    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
);

-- schema_versions
CREATE TABLE schema_versions (
    version_id INTEGER PRIMARY KEY AUTOINCREMENT,
    version_number TEXT NOT NULL UNIQUE,
    migration_file TEXT NOT NULL,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    description TEXT,
    checksum TEXT  -- SHA256 of migration file for integrity
);

-- score_history
CREATE TABLE score_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL,
    game_id TEXT NOT NULL,
    action_number INTEGER NOT NULL,
    score REAL NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES training_sessions(session_id)
);

-- scorecard_analysis_history
CREATE TABLE scorecard_analysis_history (
            analysis_id INTEGER PRIMARY KEY AUTOINCREMENT,
            analysis_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            total_scorecards INTEGER,
            problem_count INTEGER,
            zero_levels INTEGER,
            zero_actions INTEGER,
            excessive_actions INTEGER,
            details TEXT
        );

-- sensation_learning_events
CREATE TABLE sensation_learning_events (
        event_id TEXT PRIMARY KEY,
        agent_id TEXT NOT NULL,
        game_id TEXT NOT NULL,
        generation INTEGER NOT NULL,
        
        -- Sensation context
        object_type TEXT NOT NULL,
        pre_sensation_score REAL NOT NULL,
        post_sensation_score REAL NOT NULL,
        
        -- Navigation context  
        pre_navigation_state REAL NOT NULL,
        post_navigation_state REAL NOT NULL,
        action_taken INTEGER NOT NULL, -- 1-7 only
        
        -- Learning outcome
        reward_received REAL NOT NULL,
        sensation_adjustment REAL NOT NULL,
        learning_success BOOLEAN DEFAULT FALSE,
        
        -- Timestamps
        event_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
        
        FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
    );

-- sequence_dependencies
CREATE TABLE sequence_dependencies (
            dependency_id TEXT PRIMARY KEY,
            parent_sequence_id TEXT NOT NULL,
            child_sequence_id TEXT NOT NULL,
            dependency_type TEXT NOT NULL CHECK(dependency_type IN ('chain', 'variation', 'synthesis')),
            
            combined_efficiency REAL DEFAULT 0.0,
            improvement_over_parent REAL DEFAULT 0.0,
            discovery_agent_id TEXT,
            discovery_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            discovery_generation INTEGER DEFAULT 0,
            
            times_used INTEGER DEFAULT 0,
            success_rate REAL DEFAULT 0.0,
            viral_spread_count INTEGER DEFAULT 0,
            
            is_beneficial BOOLEAN DEFAULT NULL,
            fitness_impact REAL DEFAULT 0.0,
            
            FOREIGN KEY (parent_sequence_id) REFERENCES winning_sequences(sequence_id),
            FOREIGN KEY (child_sequence_id) REFERENCES winning_sequences(sequence_id),
            FOREIGN KEY (discovery_agent_id) REFERENCES agents(agent_id)
        );

-- sequence_reputation
CREATE TABLE sequence_reputation (
    sequence_id TEXT PRIMARY KEY,
    
    -- Validation statistics
    total_validation_attempts INTEGER DEFAULT 0,
    successful_validations INTEGER DEFAULT 0,
    failed_validations INTEGER DEFAULT 0,
    partial_validations INTEGER DEFAULT 0,
    
    -- Reputation metrics
    success_rate REAL DEFAULT 0.0,              -- successful / total
    reliability_score REAL DEFAULT 0.5,         -- Bayesian confidence-adjusted score
    agent_diversity INTEGER DEFAULT 1,          -- How many different agents tried it
    
    -- Temporal tracking
    recent_success_rate REAL DEFAULT 0.0,       -- Last 10 attempts only
    trending TEXT DEFAULT 'stable',             -- 'improving', 'declining', 'stable'
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (sequence_id) REFERENCES winning_sequences(sequence_id)
);

-- sequence_validation_attempts
CREATE TABLE sequence_validation_attempts (
    validation_id TEXT PRIMARY KEY,
    sequence_id TEXT NOT NULL,
    agent_id TEXT NOT NULL,
    game_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    attempted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Validation results
    validation_success BOOLEAN NOT NULL,       -- Did sequence work for this agent?
    partial_success BOOLEAN DEFAULT FALSE,     -- Got partway through sequence
    actions_completed INTEGER DEFAULT 0,       -- How many actions from sequence worked
    total_actions_in_sequence INTEGER NOT NULL,
    
    -- Performance
    score_achieved REAL DEFAULT 0.0,
    efficiency_vs_original REAL DEFAULT 1.0,   -- This agent's efficiency / original efficiency
    
    -- Context
    agent_epigenetics TEXT,                    -- JSON: agent's epigenetic state during attempt
    failure_reason TEXT,                       -- If failed, why? 'state_mismatch', 'invalid_action', etc.
    
    FOREIGN KEY (sequence_id) REFERENCES winning_sequences(sequence_id),
    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
);

-- sequence_validation_queue
CREATE TABLE sequence_validation_queue (
    queue_id INTEGER PRIMARY KEY AUTOINCREMENT,
    sequence_id TEXT NOT NULL,
    game_id TEXT NOT NULL,
    priority INTEGER DEFAULT 5,  -- 1-10, higher = more urgent
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_validated_at TIMESTAMP,
    validation_count INTEGER DEFAULT 0,
    status TEXT DEFAULT 'pending',  -- pending, in_progress, completed, failed
    
    FOREIGN KEY (sequence_id) REFERENCES winning_sequences(sequence_id)
);

-- signal_propagation_events
CREATE TABLE signal_propagation_events (
        propagation_id TEXT PRIMARY KEY,
        signal_id TEXT NOT NULL,
        propagation_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        generation INTEGER NOT NULL,
        source_agent_id TEXT,
        target_agent_id TEXT NOT NULL,
        propagation_distance INTEGER DEFAULT 1,
        signal_strength_before REAL NOT NULL,
        signal_strength_after REAL NOT NULL,
        modification_type TEXT DEFAULT 'relay',
        agent_relationship TEXT DEFAULT 'random',
        transmission_probability REAL DEFAULT 1.0,
        FOREIGN KEY (signal_id) REFERENCES network_regulatory_signals(signal_id),
        FOREIGN KEY (source_agent_id) REFERENCES agents(agent_id),
        FOREIGN KEY (target_agent_id) REFERENCES agents(agent_id)
    );

-- subgoal_executions
CREATE TABLE subgoal_executions (
                    execution_id TEXT PRIMARY KEY,
                    plan_id TEXT NOT NULL,
                    subgoal_index INTEGER NOT NULL,
                    agent_id TEXT NOT NULL,
                    game_id TEXT NOT NULL,
                    
                    -- Subgoal details
                    subgoal_type TEXT NOT NULL,  -- 'identify_pattern', 'fill_region', 'transform', etc.
                    subgoal_description TEXT NOT NULL,
                    preconditions TEXT,  -- JSON: what must be true before
                    postconditions TEXT,  -- JSON: what should be true after
                    
                    -- Execution
                    actions_taken TEXT,  -- JSON: list of actions executed
                    execution_status TEXT NOT NULL,  -- 'success', 'partial', 'failed'
                    score_before REAL DEFAULT 0.0,
                    score_after REAL DEFAULT 0.0,
                    score_delta REAL DEFAULT 0.0,
                    
                    -- Learning
                    success_factors TEXT,  -- JSON: what worked
                    failure_factors TEXT,  -- JSON: what didn't work
                    
                    -- Timestamps
                    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    completed_at TIMESTAMP,
                    
                    FOREIGN KEY (plan_id) REFERENCES subgoal_plans(plan_id),
                    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
                );

-- subgoal_patterns
CREATE TABLE subgoal_patterns (
                    pattern_id TEXT PRIMARY KEY,
                    pattern_name TEXT NOT NULL,
                    
                    -- Pattern structure
                    subgoal_sequence TEXT NOT NULL,  -- JSON: ordered subgoals
                    game_context TEXT,  -- JSON: when this pattern applies
                    
                    -- Effectiveness
                    times_attempted INTEGER DEFAULT 0,
                    times_succeeded INTEGER DEFAULT 0,
                    success_rate REAL DEFAULT 0.0,
                    avg_score_improvement REAL DEFAULT 0.0,
                    avg_actions_required REAL DEFAULT 0.0,
                    
                    -- Discovery
                    discovered_by_agent TEXT,
                    discovered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    discovered_generation INTEGER DEFAULT 0,
                    
                    -- Usage
                    last_used TIMESTAMP,
                    is_active BOOLEAN DEFAULT TRUE,
                    
                    FOREIGN KEY (discovered_by_agent) REFERENCES agents(agent_id)
                );

-- subgoal_plans
CREATE TABLE subgoal_plans (
                    plan_id TEXT PRIMARY KEY,
                    agent_id TEXT NOT NULL,
                    game_id TEXT NOT NULL,
                    session_id TEXT NOT NULL,
                    generation INTEGER DEFAULT 0,
                    
                    -- Plan structure
                    high_level_objective TEXT NOT NULL,
                    subgoal_sequence TEXT NOT NULL,  -- JSON: ordered list of subgoals
                    total_subgoals INTEGER NOT NULL,
                    
                    -- Execution tracking
                    plan_status TEXT DEFAULT 'active',  -- 'active', 'completed', 'failed', 'abandoned'
                    current_subgoal_index INTEGER DEFAULT 0,
                    completed_subgoals INTEGER DEFAULT 0,
                    failed_subgoals INTEGER DEFAULT 0,
                    
                    -- Performance
                    actions_planned INTEGER DEFAULT 0,
                    actions_executed INTEGER DEFAULT 0,
                    score_at_start REAL DEFAULT 0.0,
                    score_at_end REAL DEFAULT 0.0,
                    plan_efficiency REAL DEFAULT 0.0,
                    
                    -- Timestamps
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    completed_at TIMESTAMP,
                    
                    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
                );

-- system_logs
CREATE TABLE system_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    level TEXT NOT NULL,
    logger_name TEXT NOT NULL,
    message TEXT NOT NULL,
    module TEXT,
    function_name TEXT,
    line_number INTEGER,
    session_id TEXT,
    game_id TEXT,
    process_id INTEGER,
    thread_id INTEGER,
    extra_data TEXT -- JSON for additional context
);

-- training_sessions
CREATE TABLE training_sessions (
    session_id TEXT PRIMARY KEY,
    game_id TEXT, -- Optional game_id for session context
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    mode TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'running',
    total_actions INTEGER DEFAULT 0,
    total_wins INTEGER DEFAULT 0,
    total_games INTEGER DEFAULT 0,
    win_rate REAL DEFAULT 0.0,
    avg_score REAL DEFAULT 0.0,
    energy_level REAL DEFAULT 100.0,
    memory_operations INTEGER DEFAULT 0,
    sleep_cycles INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- viral_information_packages
CREATE TABLE viral_information_packages (
    package_id TEXT PRIMARY KEY,
    package_name TEXT NOT NULL,
    package_type TEXT NOT NULL,  -- 'action_sequence', 'coordinate_pattern', 'meta_strategy'
    
    -- Package content (what does this virus carry?)
    action_sequence TEXT,  -- JSON array of action IDs (e.g., [1,2,6,6,3])
    coordinate_pattern TEXT,  -- JSON array of (x,y) coordinates
    meta_strategy_description TEXT,  -- High-level strategy description
    
    -- Package characteristics
    virulence REAL DEFAULT 0.5,  -- How strongly does this influence host behavior? (0-1)
    transmission_rate REAL DEFAULT 0.3,  -- How easily does this spread? (0-1)
    mutation_rate REAL DEFAULT 0.05,  -- How stable is this package? (0-1)
    
    -- Package fitness (network-level evaluation)
    success_rate REAL DEFAULT 0.0,  -- % of hosts that succeed using this
    avg_score_contribution REAL DEFAULT 0.0,  -- Average score boost from this package
    total_infections INTEGER DEFAULT 0,  -- How many agents carry this?
    active_infections INTEGER DEFAULT 0,  -- How many currently active carriers?
    
    -- Origins and evolution
    discovery_generation INTEGER NOT NULL,
    source_sequence_id TEXT,  -- Original winning_sequence this came from
    parent_package_id TEXT,  -- If this is a mutated variant
    generation_discovered INTEGER NOT NULL,
    
    -- Lifecycle
    is_active BOOLEAN DEFAULT TRUE,
    obsolescence_score REAL DEFAULT 0.0,  -- Is this package becoming irrelevant?
    last_successful_use_generation INTEGER,
    
    FOREIGN KEY (source_sequence_id) REFERENCES winning_sequences(sequence_id),
    FOREIGN KEY (parent_package_id) REFERENCES viral_information_packages(package_id)
);

-- viral_package_interactions
CREATE TABLE viral_package_interactions (
    package_a_id TEXT NOT NULL,
    package_b_id TEXT NOT NULL,
    
    interaction_type TEXT NOT NULL,  -- 'synergistic', 'antagonistic', 'neutral'
    interaction_strength REAL DEFAULT 0.0,  -- -1.0 (interfere) to +1.0 (synergy)
    
    -- Evidence
    co_infection_count INTEGER DEFAULT 0,  -- Times both packages in same host
    synergy_score_boost REAL DEFAULT 0.0,  -- Extra score when both present
    observations INTEGER DEFAULT 0,
    
    PRIMARY KEY (package_a_id, package_b_id),
    FOREIGN KEY (package_a_id) REFERENCES viral_information_packages(package_id),
    FOREIGN KEY (package_b_id) REFERENCES viral_information_packages(package_id)
);

-- visual_primitives
CREATE TABLE visual_primitives (
    primitive_id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL,
    primitive_type TEXT NOT NULL,          -- 'symmetry_detector', 'pattern_finder', 'color_analyzer'
    primitive_name TEXT NOT NULL,
    learned_parameters TEXT NOT NULL,      -- JSON: parameters/weights for this primitive
    success_rate REAL DEFAULT 0.0,
    times_used INTEGER DEFAULT 0,
    avg_confidence REAL DEFAULT 0.0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_used TIMESTAMP,
    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
);

-- winning_sequences
CREATE TABLE winning_sequences (
    sequence_id TEXT PRIMARY KEY,
    game_id TEXT NOT NULL,
    level_number INTEGER NOT NULL,
    agent_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    discovered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- The winning sequence
    action_sequence TEXT NOT NULL,         -- JSON: ordered list of actions
    coordinate_sequence TEXT,              -- JSON: coordinates for ACTION6
    total_actions INTEGER NOT NULL,
    total_score REAL NOT NULL,
    efficiency_score REAL NOT NULL,        -- score / actions
    
    -- Game state context
    initial_frame TEXT NOT NULL,           -- JSON: starting frame state
    final_frame TEXT NOT NULL,             -- JSON: winning frame state
    frame_transitions TEXT,                -- JSON: key frame changes
    
    -- Abstraction tags (for pattern matching)
    pattern_tags TEXT,                     -- JSON: ['grid_clear', 'color_match', 'sequence_repeat']
    difficulty_level TEXT,                 -- 'easy', 'medium', 'hard'
    game_type TEXT,                        -- 'action6_only', 'mixed_actions', 'pattern_based'
    
    -- Reuse tracking
    times_referenced INTEGER DEFAULT 0,
    success_rate_when_reused REAL DEFAULT 0.0,
    last_referenced TIMESTAMP, generation_discovered INTEGER DEFAULT 0, is_recombination BOOLEAN DEFAULT 0, scorecard_id TEXT, is_uber_sequence BOOLEAN DEFAULT FALSE, is_active INTEGER DEFAULT 1,
    
    FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
);

-- winning_sequences_full_game
CREATE TABLE winning_sequences_full_game (
    sequence_id TEXT PRIMARY KEY,
    game_id TEXT NOT NULL,
    total_levels INTEGER NOT NULL, -- Represents the number of levels completed
    agent_id TEXT,
    session_id TEXT,
    discovered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    action_sequence TEXT NOT NULL, -- JSON list of actions
    coordinate_sequence TEXT, -- JSON list of coordinates
    total_actions INTEGER NOT NULL,
    total_score REAL NOT NULL,
    efficiency_score REAL,
    initial_frame TEXT, -- JSON
    final_frame TEXT, -- JSON
    frame_transitions TEXT, -- JSON
    pattern_tags TEXT, -- JSON
    difficulty_level TEXT,
    game_type TEXT,
    times_referenced INTEGER DEFAULT 0,
    success_rate_when_reused REAL DEFAULT 0.0,
    last_referenced TIMESTAMP,
    generation_discovered INTEGER DEFAULT 0,
    is_recombination BOOLEAN DEFAULT 0,
    scorecard_id TEXT,
    is_active INTEGER DEFAULT 1
);

-- Indexes

-- idx_action_bias_action
CREATE INDEX idx_action_bias_action ON action_bias_events(action_taken);

-- idx_action_bias_agent
CREATE INDEX idx_action_bias_agent ON action_bias_events(agent_id);

-- idx_action_effectiveness_action_number
CREATE INDEX idx_action_effectiveness_action_number ON action_effectiveness(action_number);

-- idx_action_effectiveness_game_id
CREATE INDEX idx_action_effectiveness_game_id ON action_effectiveness(game_id);

-- idx_action_effectiveness_success_rate
CREATE INDEX idx_action_effectiveness_success_rate ON action_effectiveness(success_rate);

-- idx_action_traces_game_id
CREATE INDEX idx_action_traces_game_id ON action_traces(game_id);

-- idx_action_traces_level
CREATE INDEX idx_action_traces_level 
            ON action_traces(game_id, session_id, level_number)
        ;

-- idx_action_traces_session_id
CREATE INDEX idx_action_traces_session_id ON action_traces(session_id);

-- idx_action_traces_timestamp
CREATE INDEX idx_action_traces_timestamp ON action_traces(timestamp);

-- idx_agent_agi_metrics_fitness
CREATE INDEX idx_agent_agi_metrics_fitness ON agent_agi_metrics(agi_fitness_score DESC);

-- idx_agent_arc_perf_agent_id
CREATE INDEX idx_agent_arc_perf_agent_id ON agent_arc_performance(agent_id);

-- idx_agent_arc_perf_timestamp
CREATE INDEX idx_agent_arc_perf_timestamp ON agent_arc_performance(game_timestamp);

-- idx_agent_arc_perf_total_reward
CREATE INDEX idx_agent_arc_perf_total_reward ON agent_arc_performance(total_evolutionary_reward);

-- idx_agent_arc_perf_win_achieved
CREATE INDEX idx_agent_arc_perf_win_achieved ON agent_arc_performance(win_achieved);

-- idx_agent_arc_performance_actions
CREATE INDEX idx_agent_arc_performance_actions ON agent_arc_performance(actions_earned, actions_spent);

-- idx_agent_budget_multiplier
CREATE INDEX idx_agent_budget_multiplier ON agents(action_budget_multiplier);

-- idx_agent_game_diversity_agent
CREATE INDEX idx_agent_game_diversity_agent ON agent_game_diversity(agent_id);

-- idx_agent_game_diversity_novel
CREATE INDEX idx_agent_game_diversity_novel ON agent_game_diversity(is_novel_game);

-- idx_agent_meta_learning_fitness
CREATE INDEX idx_agent_meta_learning_fitness ON agent_meta_learning(meta_fitness_score DESC);

-- idx_agent_meta_learning_transfer_rate
CREATE INDEX idx_agent_meta_learning_transfer_rate ON agent_meta_learning(transfer_success_rate DESC);

-- idx_agent_performance_agent
CREATE INDEX idx_agent_performance_agent ON agent_performance_history(agent_id);

-- idx_agent_performance_recorded
CREATE INDEX idx_agent_performance_recorded ON agent_performance_history(recorded_at);

-- idx_agents_agent_type
CREATE INDEX idx_agents_agent_type ON agents(agent_type);

-- idx_agents_generation
CREATE INDEX idx_agents_generation ON agents(generation);

-- idx_agents_is_active
CREATE INDEX idx_agents_is_active ON agents(is_active);

-- idx_agents_score_efficiency
CREATE INDEX idx_agents_score_efficiency ON agents(score_efficiency);

-- idx_agents_total_games_won
CREATE INDEX idx_agents_total_games_won ON agents(total_games_won);

-- idx_arc_action_accepted
CREATE INDEX idx_arc_action_accepted ON arc_action_tracking(action_accepted);

-- idx_arc_action_agent_id
CREATE INDEX idx_arc_action_agent_id ON arc_action_tracking(agent_id);

-- idx_arc_action_coordinate_valid
CREATE INDEX idx_arc_action_coordinate_valid ON arc_action_tracking(coordinate_valid);

-- idx_arc_action_timestamp
CREATE INDEX idx_arc_action_timestamp ON arc_action_tracking(action_timestamp);

-- idx_chains_generation
CREATE INDEX idx_chains_generation ON knowledge_propagation_chains(chain_start_generation);

-- idx_claude_decisions_generation
CREATE INDEX idx_claude_decisions_generation ON claude_evolution_decisions(generation);

-- idx_claude_decisions_strategy_focus
CREATE INDEX idx_claude_decisions_strategy_focus ON claude_evolution_decisions(strategy_focus);

-- idx_claude_decisions_timestamp
CREATE INDEX idx_claude_decisions_timestamp ON claude_evolution_decisions(decision_timestamp);

-- idx_claude_memory_created_at
CREATE INDEX idx_claude_memory_created_at ON claude_memory(created_at);

-- idx_claude_memory_relevance
CREATE INDEX idx_claude_memory_relevance ON claude_memory(relevance_score);

-- idx_claude_memory_type
CREATE INDEX idx_claude_memory_type ON claude_memory(memory_type);

-- idx_collective_proposals_accepted
CREATE INDEX idx_collective_proposals_accepted ON collective_action_proposals(proposal_accepted);

-- idx_collective_proposals_session
CREATE INDEX idx_collective_proposals_session ON collective_action_proposals(session_id);

-- idx_collective_sessions_game
CREATE INDEX idx_collective_sessions_game ON collective_reasoning_sessions(game_id);

-- idx_collective_sessions_status
CREATE INDEX idx_collective_sessions_status ON collective_reasoning_sessions(session_status);

-- idx_collective_votes_proposal
CREATE INDEX idx_collective_votes_proposal ON collective_votes(proposal_id);

-- idx_counterfactual_agent
CREATE INDEX idx_counterfactual_agent ON counterfactual_scenarios(agent_id);

-- idx_counterfactual_game
CREATE INDEX idx_counterfactual_game ON counterfactual_scenarios(game_id);

-- idx_counterfactual_priority
CREATE INDEX idx_counterfactual_priority ON counterfactual_scenarios(priority DESC);

-- idx_counterfactual_tested
CREATE INDEX idx_counterfactual_tested ON counterfactual_scenarios(was_tested);

-- idx_curriculum_progress_agent
CREATE INDEX idx_curriculum_progress_agent ON curriculum_progress(agent_id);

-- idx_curriculum_progress_completed
CREATE INDEX idx_curriculum_progress_completed ON curriculum_progress(stage_completed);

-- idx_curriculum_progress_stage
CREATE INDEX idx_curriculum_progress_stage ON curriculum_progress(stage_number);

-- idx_decision_points_agent
CREATE INDEX idx_decision_points_agent ON decision_points(agent_id);

-- idx_decision_points_importance
CREATE INDEX idx_decision_points_importance ON decision_points(importance_score DESC);

-- idx_discovered_patterns_success_rate
CREATE INDEX idx_discovered_patterns_success_rate ON discovered_patterns(success_rate);

-- idx_ecosystem_health_generation
CREATE INDEX idx_ecosystem_health_generation ON ecosystem_health_snapshots(generation);

-- idx_ecosystem_health_score
CREATE INDEX idx_ecosystem_health_score ON ecosystem_health_snapshots(health_score DESC);

-- idx_ecosystem_health_status
CREATE INDEX idx_ecosystem_health_status ON ecosystem_health_snapshots(health_status);

-- idx_ecosystem_health_timestamp
CREATE INDEX idx_ecosystem_health_timestamp ON ecosystem_health_snapshots(snapshot_timestamp);

-- idx_ecosystem_metabolism_generation
CREATE INDEX idx_ecosystem_metabolism_generation ON ecosystem_metabolism_snapshots(generation);

-- idx_frustration_states_frustrated
CREATE INDEX idx_frustration_states_frustrated ON agent_frustration_states(is_frustrated);

-- idx_frustration_states_level
CREATE INDEX idx_frustration_states_level ON agent_frustration_states(frustration_level DESC);

-- idx_game_exposure_retired
CREATE INDEX idx_game_exposure_retired ON game_exposure_history(is_retired);

-- idx_game_results_final_score
CREATE INDEX idx_game_results_final_score ON game_results(final_score);

-- idx_game_results_scorecard
CREATE INDEX idx_game_results_scorecard ON game_results(scorecard_id);

-- idx_game_results_session_id
CREATE INDEX idx_game_results_session_id ON game_results(session_id);

-- idx_game_results_status
CREATE INDEX idx_game_results_status ON game_results(status);

-- idx_game_visual_analysis_agent
CREATE INDEX idx_game_visual_analysis_agent ON game_visual_analysis(agent_id);

-- idx_game_visual_analysis_game
CREATE INDEX idx_game_visual_analysis_game ON game_visual_analysis(game_id);

-- idx_infections_active
CREATE INDEX idx_infections_active ON agent_viral_infections(is_active);

-- idx_infections_agent
CREATE INDEX idx_infections_agent ON agent_viral_infections(agent_id);

-- idx_infections_package
CREATE INDEX idx_infections_package ON agent_viral_infections(package_id);

-- idx_knowledge_graph_source
CREATE INDEX idx_knowledge_graph_source ON knowledge_graph_edges(source_knowledge_id);

-- idx_knowledge_graph_target
CREATE INDEX idx_knowledge_graph_target ON knowledge_graph_edges(target_knowledge_id);

-- idx_knowledge_graph_type
CREATE INDEX idx_knowledge_graph_type ON knowledge_graph_edges(edge_type);

-- idx_knowledge_redundancy_criticality
CREATE INDEX idx_knowledge_redundancy_criticality ON knowledge_redundancy(criticality_score DESC);

-- idx_knowledge_redundancy_risk
CREATE INDEX idx_knowledge_redundancy_risk ON knowledge_redundancy(risk_of_loss DESC);

-- idx_knowledge_redundancy_viral_core
CREATE INDEX idx_knowledge_redundancy_viral_core ON knowledge_redundancy(is_viral_core);

-- idx_learned_rules_agent
CREATE INDEX idx_learned_rules_agent ON learned_rules(agent_id);

-- idx_learned_rules_confidence
CREATE INDEX idx_learned_rules_confidence ON learned_rules(confidence DESC);

-- idx_learned_rules_generality
CREATE INDEX idx_learned_rules_generality ON learned_rules(generality_score DESC);

-- idx_learned_rules_transferred
CREATE INDEX idx_learned_rules_transferred ON learned_rules(transferred_successfully);

-- idx_mode_agent_gen
CREATE INDEX idx_mode_agent_gen 
            ON agent_operating_modes(agent_id, generation)
        ;

-- idx_navigation_history_agent
CREATE INDEX idx_navigation_history_agent ON navigation_state_history(agent_id);

-- idx_near_miss_agent
CREATE INDEX idx_near_miss_agent ON near_miss_games(agent_id);

-- idx_near_miss_category
CREATE INDEX idx_near_miss_category ON near_miss_games(near_miss_category);

-- idx_near_miss_game
CREATE INDEX idx_near_miss_game ON near_miss_games(game_id);

-- idx_near_miss_insights_agent
CREATE INDEX idx_near_miss_insights_agent ON near_miss_insights(agent_id);

-- idx_near_miss_patterns_active
CREATE INDEX idx_near_miss_patterns_active ON near_miss_patterns(is_active);

-- idx_near_miss_score
CREATE INDEX idx_near_miss_score ON near_miss_games(final_score DESC);

-- idx_object_mappings_agent
CREATE INDEX idx_object_mappings_agent ON object_sensation_mappings(agent_id);

-- idx_optimization_game_level
CREATE INDEX idx_optimization_game_level 
            ON optimization_status(game_id, level_number)
        ;

-- idx_optimization_status
CREATE INDEX idx_optimization_status 
            ON optimization_status(is_optimized, generations_without_improvement)
        ;

-- idx_pariah_awareness_active
CREATE INDEX idx_pariah_awareness_active ON agent_pariah_awareness(is_active);

-- idx_pariah_awareness_agent
CREATE INDEX idx_pariah_awareness_agent ON agent_pariah_awareness(agent_id);

-- idx_pariah_awareness_pariah
CREATE INDEX idx_pariah_awareness_pariah ON agent_pariah_awareness(pariah_id);

-- idx_pariahs_active
CREATE INDEX idx_pariahs_active ON pariahs(is_active);

-- idx_pariahs_toxicity
CREATE INDEX idx_pariahs_toxicity ON pariahs(toxicity DESC);

-- idx_pariahs_type
CREATE INDEX idx_pariahs_type ON pariahs(pariah_type);

-- idx_pattern_applications_success
CREATE INDEX idx_pattern_applications_success ON pattern_applications(success);

-- idx_pattern_synthesis_patterns
CREATE INDEX idx_pattern_synthesis_patterns ON pattern_synthesis(pattern_a_id, pattern_b_id);

-- idx_pop_health_generation
CREATE INDEX idx_pop_health_generation ON population_health_metrics(generation);

-- idx_pop_health_improvement_rate
CREATE INDEX idx_pop_health_improvement_rate ON population_health_metrics(improvement_rate);

-- idx_pop_health_timestamp
CREATE INDEX idx_pop_health_timestamp ON population_health_metrics(measurement_timestamp);

-- idx_propagation_generation
CREATE INDEX idx_propagation_generation ON signal_propagation_events(generation);

-- idx_quorum_events_generation
CREATE INDEX idx_quorum_events_generation ON frustration_quorum_events(generation);

-- idx_quorum_events_reached
CREATE INDEX idx_quorum_events_reached ON frustration_quorum_events(quorum_reached);

-- idx_recombination_attempts_agent
CREATE INDEX idx_recombination_attempts_agent ON recombination_attempts(agent_id, generation);

-- idx_recombination_attempts_game
CREATE INDEX idx_recombination_attempts_game ON recombination_attempts(game_id);

-- idx_regulation_generation
CREATE INDEX idx_regulation_generation ON network_regulation_history(generation);

-- idx_responses_agent
CREATE INDEX idx_responses_agent ON agent_signal_responses(agent_id, generation);

-- idx_responses_generation
CREATE INDEX idx_responses_generation ON agent_signal_responses(generation);

-- idx_rule_redundancy_criticality
CREATE INDEX idx_rule_redundancy_criticality ON rule_redundancy(criticality_score DESC);

-- idx_rule_redundancy_viral_core
CREATE INDEX idx_rule_redundancy_viral_core ON rule_redundancy(is_viral_core);

-- idx_rule_transfers_rule
CREATE INDEX idx_rule_transfers_rule ON rule_transfers(rule_id);

-- idx_rule_transfers_successful
CREATE INDEX idx_rule_transfers_successful ON rule_transfers(transfer_successful);

-- idx_rule_transfers_timestamp
CREATE INDEX idx_rule_transfers_timestamp ON rule_transfers(transfer_timestamp);

-- idx_score_history_game_id
CREATE INDEX idx_score_history_game_id ON score_history(game_id);

-- idx_score_history_session_id
CREATE INDEX idx_score_history_session_id ON score_history(session_id);

-- idx_score_history_timestamp
CREATE INDEX idx_score_history_timestamp ON score_history(timestamp);

-- idx_sensation_events_agent
CREATE INDEX idx_sensation_events_agent ON sensation_learning_events(agent_id);

-- idx_sensation_events_generation
CREATE INDEX idx_sensation_events_generation ON sensation_learning_events(generation);

-- idx_sequence_dependencies_agent
CREATE INDEX idx_sequence_dependencies_agent ON sequence_dependencies(discovery_agent_id, discovery_generation);

-- idx_sequence_dependencies_child
CREATE INDEX idx_sequence_dependencies_child ON sequence_dependencies(child_sequence_id);

-- idx_sequence_dependencies_parent
CREATE INDEX idx_sequence_dependencies_parent ON sequence_dependencies(parent_sequence_id);

-- idx_sequence_reputation_success_rate
CREATE INDEX idx_sequence_reputation_success_rate ON sequence_reputation(success_rate DESC);

-- idx_sequence_validation_attempts_agent
CREATE INDEX idx_sequence_validation_attempts_agent ON sequence_validation_attempts(agent_id);

-- idx_sequence_validation_attempts_sequence
CREATE INDEX idx_sequence_validation_attempts_sequence ON sequence_validation_attempts(sequence_id);

-- idx_signals_active
CREATE INDEX idx_signals_active ON network_regulatory_signals(is_active, generation);

-- idx_signals_generation
CREATE INDEX idx_signals_generation ON network_regulatory_signals(generation);

-- idx_subgoal_executions_plan
CREATE INDEX idx_subgoal_executions_plan ON subgoal_executions(plan_id);

-- idx_subgoal_patterns_success
CREATE INDEX idx_subgoal_patterns_success ON subgoal_patterns(success_rate DESC);

-- idx_subgoal_plans_agent
CREATE INDEX idx_subgoal_plans_agent ON subgoal_plans(agent_id);

-- idx_subgoal_plans_game
CREATE INDEX idx_subgoal_plans_game ON subgoal_plans(game_id);

-- idx_subgoal_plans_status
CREATE INDEX idx_subgoal_plans_status ON subgoal_plans(plan_status);

-- idx_system_logs_game_id
CREATE INDEX idx_system_logs_game_id ON system_logs(game_id);

-- idx_system_logs_level
CREATE INDEX idx_system_logs_level ON system_logs(level);

-- idx_system_logs_logger_name
CREATE INDEX idx_system_logs_logger_name ON system_logs(logger_name);

-- idx_system_logs_session_id
CREATE INDEX idx_system_logs_session_id ON system_logs(session_id);

-- idx_system_logs_timestamp
CREATE INDEX idx_system_logs_timestamp ON system_logs(timestamp);

-- idx_training_sessions_mode
CREATE INDEX idx_training_sessions_mode ON training_sessions(mode);

-- idx_training_sessions_start_time
CREATE INDEX idx_training_sessions_start_time ON training_sessions(start_time);

-- idx_training_sessions_status
CREATE INDEX idx_training_sessions_status ON training_sessions(status);

-- idx_transfers_donor
CREATE INDEX idx_transfers_donor ON horizontal_transfer_events(donor_agent_id);

-- idx_transfers_generation
CREATE INDEX idx_transfers_generation ON horizontal_transfer_events(generation);

-- idx_transfers_recipient
CREATE INDEX idx_transfers_recipient ON horizontal_transfer_events(recipient_agent_id);

-- idx_validation_queue_sequence
CREATE INDEX idx_validation_queue_sequence ON sequence_validation_queue(sequence_id);

-- idx_validation_queue_status
CREATE INDEX idx_validation_queue_status ON sequence_validation_queue(status, priority DESC);

-- idx_viral_packages_active
CREATE INDEX idx_viral_packages_active ON viral_information_packages(is_active);

-- idx_viral_packages_success
CREATE INDEX idx_viral_packages_success ON viral_information_packages(success_rate DESC);

-- idx_viral_packages_type
CREATE INDEX idx_viral_packages_type ON viral_information_packages(package_type);

-- idx_visual_primitives_agent
CREATE INDEX idx_visual_primitives_agent ON visual_primitives(agent_id);

-- idx_visual_primitives_success
CREATE INDEX idx_visual_primitives_success ON visual_primitives(success_rate DESC);

-- idx_visual_primitives_type
CREATE INDEX idx_visual_primitives_type ON visual_primitives(primitive_type);

-- idx_winning_sequences_efficiency
CREATE INDEX idx_winning_sequences_efficiency ON winning_sequences(efficiency_score);

-- idx_winning_sequences_full_game_game_id
CREATE INDEX idx_winning_sequences_full_game_game_id ON winning_sequences_full_game(game_id);

-- idx_winning_sequences_game
CREATE INDEX idx_winning_sequences_game ON winning_sequences(game_id, level_number);

-- idx_winning_sequences_game_id
CREATE INDEX idx_winning_sequences_game_id ON winning_sequences(game_id);

-- idx_winning_sequences_scorecard
CREATE INDEX idx_winning_sequences_scorecard ON winning_sequences(scorecard_id);
