#!/usr/bin/env python3
"""
Database Schema Auto-Export Tool

Automatically exports complete database schema to complete_database_schema.sql
Run this after any schema modifications.

Usage:
    python export_schema.py > new_schema.sql
    # OR update directly:
    python update_schema.py
"""

import sqlite3
from datetime import datetime

def export_schema():
    """Export complete database schema to SQL"""
    db = sqlite3.connect('core_data.db')
    
    schema_lines = []
    
    # Header
    schema_lines.append("-- " + "=" * 76)
    schema_lines.append("-- BitterTruth-AI Ouroboros System - Complete Database Schema")
    schema_lines.append("-- " + "="  * 76)
    schema_lines.append("-- ")
    schema_lines.append(f"-- Last Updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    schema_lines.append("-- Auto-generated by export_schema.py")
    schema_lines.append("-- ")
    schema_lines.append("-- Rule 2 Compliance: All data stored in SQLite database (core_data.db)")
    schema_lines.append("-- No file-based logging or persistence")
    schema_lines.append("-- " + "=" * 76)
    schema_lines.append("")
    
    # Get all tables
    cursor = db.cursor()
    cursor.execute("SELECT name, sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
    tables = cursor.fetchall()
    
    schema_lines.append(f"-- Total Tables: {len(tables)}")
    schema_lines.append("")
    
    # Export each table
    for table_name, create_sql in tables:
        if create_sql:
            schema_lines.append(f"-- {table_name}")
            schema_lines.append(create_sql + ";")
            schema_lines.append("")
    
    # Get all indexes
    cursor.execute("SELECT name, sql FROM sqlite_master WHERE type='index' AND name NOT LIKE 'sqlite_%' ORDER BY name")
    indexes = cursor.fetchall()
    
    if indexes:
        schema_lines.append("-- Indexes")
        schema_lines.append("")
        for index_name, create_sql in indexes:
            if create_sql:  # Skip auto-created indexes
                schema_lines.append(f"-- {index_name}")
                schema_lines.append(create_sql + ";")
                schema_lines.append("")
    
    db.close()
    return "\n".join(schema_lines)

def update_schema_file():
    """Update complete_database_schema.sql with current schema"""
    schema = export_schema()
    
    with open('complete_database_schema.sql', 'w', encoding='utf-8') as f:
        f.write(schema)
    
    print(f"✅ Schema exported to complete_database_schema.sql")
    print(f"   Tables: {schema.count('CREATE TABLE')}")
    print(f"   Indexes: {schema.count('CREATE INDEX')}")

if __name__ == '__main__':
    import sys
    
    if '--update' in sys.argv or len(sys.argv) == 1:
        update_schema_file()
    else:
        # Print to stdout for piping
        print(export_schema())
