#!/usr/bin/env python3
"""
Database Schema Auto-Export Tool

Automatically exports complete database schema to complete_database_schema.sql
Run this after any schema modifications.

Usage:
    python export_schema.py > new_schema.sql
    # OR update directly:
    python update_schema.py
"""

import sqlite3
from datetime import datetime


def export_schema():
    """Export complete database schema to SQL"""
    db = sqlite3.connect("core_data.db")

    schema_lines = []

    # Header
    schema_lines.append("-- " + "=" * 76)
    schema_lines.append("-- BitterTruth-AI Ouroboros System - Complete Database Schema")
    schema_lines.append("-- " + "=" * 76)
    schema_lines.append("-- ")
    schema_lines.append(
        f"-- Last Updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )
    schema_lines.append("-- Auto-generated by export_schema.py")
    schema_lines.append("-- ")
    schema_lines.append(
        "-- Rule 2 Compliance: All data stored in SQLite database (core_data.db)"
    )
    schema_lines.append("-- No file-based logging or persistence")
    schema_lines.append("-- " + "=" * 76)
    schema_lines.append("")

    # Get all tables
    cursor = db.cursor()
    cursor.execute(
        "SELECT name, sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
    )
    tables = cursor.fetchall()

    schema_lines.append(f"-- Total Tables: {len(tables)}")
    schema_lines.append("")

    # Export each table
    for table_name, create_sql in tables:
        if create_sql:
            schema_lines.append(f"-- {table_name}")
            schema_lines.append(create_sql + ";")
            schema_lines.append("")

    # Get all indexes
    cursor.execute(
        "SELECT name, sql FROM sqlite_master WHERE type='index' AND name NOT LIKE 'sqlite_%' ORDER BY name"
    )
    indexes = cursor.fetchall()

    if indexes:
        schema_lines.append("-- Indexes")
        schema_lines.append("")
        for index_name, create_sql in indexes:
            if create_sql:  # Skip auto-created indexes
                schema_lines.append(f"-- {index_name}")
                schema_lines.append(create_sql + ";")
                schema_lines.append("")

    db.close()
    return "\n".join(schema_lines)


def update_schema_file():
    """Update complete_database_schema.sql with current schema"""
    schema = export_schema()

    with open("complete_database_schema.sql", "w", encoding="utf-8") as f:
        f.write(schema)

    table_count = schema.count("CREATE TABLE")
    index_count = schema.count("CREATE INDEX")

    print(f"✅ Schema exported to complete_database_schema.sql")
    print(f"   Tables: {table_count}")
    print(f"   Indexes: {index_count}")

    # TASK #5: Log schema version to database
    try:
        import hashlib

        schema_hash = hashlib.sha256(schema.encode()).hexdigest()[:16]

        db = sqlite3.connect("core_data.db")
        cursor = db.cursor()

        # Get latest version number
        cursor.execute(
            "SELECT MAX(CAST(version_number AS INTEGER)) as max_ver FROM schema_versions WHERE version_number GLOB '[0-9]*'"
        )
        result = cursor.fetchone()
        latest_ver = result[0] if result[0] else 0
        next_ver = str(latest_ver + 1).zfill(3)

        # Insert new version record
        cursor.execute(
            """
            INSERT OR IGNORE INTO schema_versions (version_number, migration_file, description, checksum)
            VALUES (?, ?, ?, ?)
        """,
            (
                next_ver,
                "auto_export",
                f"Auto-export: {table_count} tables, {index_count} indexes",
                schema_hash,
            ),
        )

        db.commit()
        db.close()

        print(f"   Version: {next_ver} (checksum: {schema_hash})")
    except Exception as e:
        print(f"   Warning: Could not log schema version: {e}")


if __name__ == "__main__":
    import sys

    if "--update" in sys.argv or len(sys.argv) == 1:
        update_schema_file()
    else:
        # Print to stdout for piping
        print(export_schema())
